// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_AGUS_MAPS_API_G_H_
#define PIGEON_AGUS_MAPS_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace agus_maps_flutter {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Rendering activity state for low-frequency notifications.
enum class RenderState {
  // Rendering is active (frames expected).
  kActive = 0,
  // Rendering is idle (no frames expected).
  kIdle = 1
};


// Request payload for creating a map surface.
//
// Generated class from Pigeon that represents data sent in messages.
class CreateMapSurfaceRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  CreateMapSurfaceRequest();

  // Constructs an object setting all fields.
  explicit CreateMapSurfaceRequest(
    const int64_t* width,
    const int64_t* height,
    const double* density);

  const int64_t* width() const;
  void set_width(const int64_t* value_arg);
  void set_width(int64_t value_arg);

  const int64_t* height() const;
  void set_height(const int64_t* value_arg);
  void set_height(int64_t value_arg);

  const double* density() const;
  void set_density(const double* value_arg);
  void set_density(double value_arg);

 private:
  static CreateMapSurfaceRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> width_;
  std::optional<int64_t> height_;
  std::optional<double> density_;
};


// Request payload for resizing a map surface.
//
// Generated class from Pigeon that represents data sent in messages.
class ResizeMapSurfaceRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ResizeMapSurfaceRequest(
    int64_t width,
    int64_t height);

  // Constructs an object setting all fields.
  explicit ResizeMapSurfaceRequest(
    int64_t width,
    int64_t height,
    const double* density);

  int64_t width() const;
  void set_width(int64_t value_arg);

  int64_t height() const;
  void set_height(int64_t value_arg);

  const double* density() const;
  void set_density(const double* value_arg);
  void set_density(double value_arg);

 private:
  static ResizeMapSurfaceRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t width_;
  int64_t height_;
  std::optional<double> density_;
};


// Stable identifier for a place page feature.
//
// Generated class from Pigeon that represents data sent in messages.
class PlacePageFeatureId {
 public:
  // Constructs an object setting all fields.
  explicit PlacePageFeatureId(
    const std::string& mwm_name,
    int64_t mwm_version,
    int64_t index);

  const std::string& mwm_name() const;
  void set_mwm_name(std::string_view value_arg);

  int64_t mwm_version() const;
  void set_mwm_version(int64_t value_arg);

  int64_t index() const;
  void set_index(int64_t value_arg);

 private:
  static PlacePageFeatureId FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlacePageData;
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string mwm_name_;
  int64_t mwm_version_;
  int64_t index_;
};


// Formatted coordinates variants for a place page.
//
// Generated class from Pigeon that represents data sent in messages.
class PlacePageCoordinates {
 public:
  // Constructs an object setting all non-nullable fields.
  PlacePageCoordinates();

  // Constructs an object setting all fields.
  explicit PlacePageCoordinates(
    const std::string* decimal,
    const std::string* dms,
    const std::string* osm,
    const std::string* olc,
    const std::string* utm,
    const std::string* mgrs);

  const std::string* decimal() const;
  void set_decimal(const std::string_view* value_arg);
  void set_decimal(std::string_view value_arg);

  const std::string* dms() const;
  void set_dms(const std::string_view* value_arg);
  void set_dms(std::string_view value_arg);

  const std::string* osm() const;
  void set_osm(const std::string_view* value_arg);
  void set_osm(std::string_view value_arg);

  const std::string* olc() const;
  void set_olc(const std::string_view* value_arg);
  void set_olc(std::string_view value_arg);

  const std::string* utm() const;
  void set_utm(const std::string_view* value_arg);
  void set_utm(std::string_view value_arg);

  const std::string* mgrs() const;
  void set_mgrs(const std::string_view* value_arg);
  void set_mgrs(std::string_view value_arg);

 private:
  static PlacePageCoordinates FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlacePageData;
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> decimal_;
  std::optional<std::string> dms_;
  std::optional<std::string> osm_;
  std::optional<std::string> olc_;
  std::optional<std::string> utm_;
  std::optional<std::string> mgrs_;
};


// Integer-keyed metadata entry.
//
// Generated class from Pigeon that represents data sent in messages.
class PlacePageIntMetadataEntry {
 public:
  // Constructs an object setting all fields.
  explicit PlacePageIntMetadataEntry(
    int64_t key,
    const std::string& value);

  int64_t key() const;
  void set_key(int64_t value_arg);

  const std::string& value() const;
  void set_value(std::string_view value_arg);

 private:
  static PlacePageIntMetadataEntry FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t key_;
  std::string value_;
};


// String-keyed metadata entry.
//
// Generated class from Pigeon that represents data sent in messages.
class PlacePageStringMetadataEntry {
 public:
  // Constructs an object setting all fields.
  explicit PlacePageStringMetadataEntry(
    const std::string& key,
    const std::string& value);

  const std::string& key() const;
  void set_key(std::string_view value_arg);

  const std::string& value() const;
  void set_value(std::string_view value_arg);

 private:
  static PlacePageStringMetadataEntry FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string key_;
  std::string value_;
};


// Structured place page payload.
//
// Generated class from Pigeon that represents data sent in messages.
class PlacePageData {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PlacePageData(
    const PlacePageFeatureId& feature_id,
    int64_t object_type,
    int64_t opening_mode,
    const std::string& title,
    const std::string& secondary_title,
    const std::string& subtitle,
    const std::string& address,
    double lat,
    double lon,
    const std::string& wiki_description_html,
    int64_t road_type,
    bool is_route_point,
    const PlacePageCoordinates& coordinates,
    const flutter::EncodableList& raw_types,
    const flutter::EncodableList& metadata,
    const flutter::EncodableList& metadata_tags);

  // Constructs an object setting all fields.
  explicit PlacePageData(
    const PlacePageFeatureId& feature_id,
    int64_t object_type,
    int64_t opening_mode,
    const std::string& title,
    const std::string& secondary_title,
    const std::string& subtitle,
    const std::string& address,
    double lat,
    double lon,
    const std::string& wiki_description_html,
    int64_t road_type,
    bool is_route_point,
    const PlacePageCoordinates& coordinates,
    const flutter::EncodableList& raw_types,
    const flutter::EncodableList& metadata,
    const flutter::EncodableList& metadata_tags,
    const int64_t* bookmark_id,
    const int64_t* bookmark_category_id,
    const int64_t* track_id);

  ~PlacePageData() = default;
  PlacePageData(const PlacePageData& other);
  PlacePageData& operator=(const PlacePageData& other);
  PlacePageData(PlacePageData&& other) = default;
  PlacePageData& operator=(PlacePageData&& other) noexcept = default;
  const PlacePageFeatureId& feature_id() const;
  void set_feature_id(const PlacePageFeatureId& value_arg);

  int64_t object_type() const;
  void set_object_type(int64_t value_arg);

  int64_t opening_mode() const;
  void set_opening_mode(int64_t value_arg);

  const std::string& title() const;
  void set_title(std::string_view value_arg);

  const std::string& secondary_title() const;
  void set_secondary_title(std::string_view value_arg);

  const std::string& subtitle() const;
  void set_subtitle(std::string_view value_arg);

  const std::string& address() const;
  void set_address(std::string_view value_arg);

  double lat() const;
  void set_lat(double value_arg);

  double lon() const;
  void set_lon(double value_arg);

  const std::string& wiki_description_html() const;
  void set_wiki_description_html(std::string_view value_arg);

  int64_t road_type() const;
  void set_road_type(int64_t value_arg);

  bool is_route_point() const;
  void set_is_route_point(bool value_arg);

  const PlacePageCoordinates& coordinates() const;
  void set_coordinates(const PlacePageCoordinates& value_arg);

  const flutter::EncodableList& raw_types() const;
  void set_raw_types(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& metadata() const;
  void set_metadata(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& metadata_tags() const;
  void set_metadata_tags(const flutter::EncodableList& value_arg);

  const int64_t* bookmark_id() const;
  void set_bookmark_id(const int64_t* value_arg);
  void set_bookmark_id(int64_t value_arg);

  const int64_t* bookmark_category_id() const;
  void set_bookmark_category_id(const int64_t* value_arg);
  void set_bookmark_category_id(int64_t value_arg);

  const int64_t* track_id() const;
  void set_track_id(const int64_t* value_arg);
  void set_track_id(int64_t value_arg);

 private:
  static PlacePageData FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class AgusMapsHostApi;
  friend class AgusMapsFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<PlacePageFeatureId> feature_id_;
  int64_t object_type_;
  int64_t opening_mode_;
  std::string title_;
  std::string secondary_title_;
  std::string subtitle_;
  std::string address_;
  double lat_;
  double lon_;
  std::string wiki_description_html_;
  int64_t road_type_;
  bool is_route_point_;
  std::unique_ptr<PlacePageCoordinates> coordinates_;
  flutter::EncodableList raw_types_;
  flutter::EncodableList metadata_;
  flutter::EncodableList metadata_tags_;
  std::optional<int64_t> bookmark_id_;
  std::optional<int64_t> bookmark_category_id_;
  std::optional<int64_t> track_id_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Host API implemented by native platforms.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class AgusMapsHostApi {
 public:
  AgusMapsHostApi(const AgusMapsHostApi&) = delete;
  AgusMapsHostApi& operator=(const AgusMapsHostApi&) = delete;
  virtual ~AgusMapsHostApi() {}
  virtual void ExtractMap(
    const std::string& asset_path,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void ExtractDataFiles(std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void GetApkPath(std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void CreateMapSurface(
    const CreateMapSurfaceRequest& request,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  virtual void ResizeMapSurface(
    const ResizeMapSurfaceRequest& request,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void DestroyMapSurface(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Returns the current place page payload if available.
  virtual void GetCurrentPlacePage(std::function<void(ErrorOr<std::optional<PlacePageData>> reply)> result) = 0;
  // Clears the active place page selection.
  virtual void ClearPlacePageSelection(std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by AgusMapsHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `AgusMapsHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    AgusMapsHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    AgusMapsHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  AgusMapsHostApi() = default;
};
// Flutter API implemented by Dart for low-frequency notifications.
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class AgusMapsFlutterApi {
 public:
  AgusMapsFlutterApi(flutter::BinaryMessenger* binary_messenger);
  AgusMapsFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnMapReady(
    int64_t surface_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnRenderStateChanged(
    const RenderState& state,
    const int64_t* surface_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnPlacePageChanged(
    const PlacePageData* place_page,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace agus_maps_flutter
#endif  // PIGEON_AGUS_MAPS_API_G_H_
