// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsAgusMapsApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashAgusMapsApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsAgusMapsApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsAgusMapsApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsAgusMapsApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsAgusMapsApi(lhsKey, rhsKey) {
          if deepEqualsAgusMapsApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsAgusMapsApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashAgusMapsApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashAgusMapsApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashAgusMapsApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashAgusMapsApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashAgusMapsApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashAgusMapsApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Rendering activity state for low-frequency notifications.
enum RenderState: Int {
  /// Rendering is active (frames expected).
  case active = 0
  /// Rendering is idle (no frames expected).
  case idle = 1
}

/// Request payload for creating a map surface.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CreateMapSurfaceRequest: Hashable {
  var width: Int64? = nil
  var height: Int64? = nil
  var density: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateMapSurfaceRequest? {
    let width: Int64? = nilOrValue(pigeonVar_list[0])
    let height: Int64? = nilOrValue(pigeonVar_list[1])
    let density: Double? = nilOrValue(pigeonVar_list[2])

    return CreateMapSurfaceRequest(
      width: width,
      height: height,
      density: density
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      density,
    ]
  }
  static func == (lhs: CreateMapSurfaceRequest, rhs: CreateMapSurfaceRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.width, rhs.width) && deepEqualsAgusMapsApi(lhs.height, rhs.height) && deepEqualsAgusMapsApi(lhs.density, rhs.density)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreateMapSurfaceRequest")
    deepHashAgusMapsApi(value: width, hasher: &hasher)
    deepHashAgusMapsApi(value: height, hasher: &hasher)
    deepHashAgusMapsApi(value: density, hasher: &hasher)
  }
}

/// Request payload for resizing a map surface.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ResizeMapSurfaceRequest: Hashable {
  var width: Int64
  var height: Int64
  var density: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ResizeMapSurfaceRequest? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64
    let density: Double? = nilOrValue(pigeonVar_list[2])

    return ResizeMapSurfaceRequest(
      width: width,
      height: height,
      density: density
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      density,
    ]
  }
  static func == (lhs: ResizeMapSurfaceRequest, rhs: ResizeMapSurfaceRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.width, rhs.width) && deepEqualsAgusMapsApi(lhs.height, rhs.height) && deepEqualsAgusMapsApi(lhs.density, rhs.density)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ResizeMapSurfaceRequest")
    deepHashAgusMapsApi(value: width, hasher: &hasher)
    deepHashAgusMapsApi(value: height, hasher: &hasher)
    deepHashAgusMapsApi(value: density, hasher: &hasher)
  }
}

/// Pointer position in the native map surface's physical pixel space.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MapPointerUpdateRequest: Hashable {
  var physicalX: Double
  var physicalY: Double
  var insideMap: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MapPointerUpdateRequest? {
    let physicalX = pigeonVar_list[0] as! Double
    let physicalY = pigeonVar_list[1] as! Double
    let insideMap = pigeonVar_list[2] as! Bool

    return MapPointerUpdateRequest(
      physicalX: physicalX,
      physicalY: physicalY,
      insideMap: insideMap
    )
  }
  func toList() -> [Any?] {
    return [
      physicalX,
      physicalY,
      insideMap,
    ]
  }
  static func == (lhs: MapPointerUpdateRequest, rhs: MapPointerUpdateRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.physicalX, rhs.physicalX) && deepEqualsAgusMapsApi(lhs.physicalY, rhs.physicalY) && deepEqualsAgusMapsApi(lhs.insideMap, rhs.insideMap)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MapPointerUpdateRequest")
    deepHashAgusMapsApi(value: physicalX, hasher: &hasher)
    deepHashAgusMapsApi(value: physicalY, hasher: &hasher)
    deepHashAgusMapsApi(value: insideMap, hasher: &hasher)
  }
}

/// Native map-space pointer projection result.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MapPointerCoordinate: Hashable {
  var physicalX: Double
  var physicalY: Double
  var insideMap: Bool
  var lat: Double
  var lon: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MapPointerCoordinate? {
    let physicalX = pigeonVar_list[0] as! Double
    let physicalY = pigeonVar_list[1] as! Double
    let insideMap = pigeonVar_list[2] as! Bool
    let lat = pigeonVar_list[3] as! Double
    let lon = pigeonVar_list[4] as! Double

    return MapPointerCoordinate(
      physicalX: physicalX,
      physicalY: physicalY,
      insideMap: insideMap,
      lat: lat,
      lon: lon
    )
  }
  func toList() -> [Any?] {
    return [
      physicalX,
      physicalY,
      insideMap,
      lat,
      lon,
    ]
  }
  static func == (lhs: MapPointerCoordinate, rhs: MapPointerCoordinate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.physicalX, rhs.physicalX) && deepEqualsAgusMapsApi(lhs.physicalY, rhs.physicalY) && deepEqualsAgusMapsApi(lhs.insideMap, rhs.insideMap) && deepEqualsAgusMapsApi(lhs.lat, rhs.lat) && deepEqualsAgusMapsApi(lhs.lon, rhs.lon)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MapPointerCoordinate")
    deepHashAgusMapsApi(value: physicalX, hasher: &hasher)
    deepHashAgusMapsApi(value: physicalY, hasher: &hasher)
    deepHashAgusMapsApi(value: insideMap, hasher: &hasher)
    deepHashAgusMapsApi(value: lat, hasher: &hasher)
    deepHashAgusMapsApi(value: lon, hasher: &hasher)
  }
}

/// Native interaction line style for transient draw/edit geometry.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DrapeInteractionLineStyle: Hashable {
  /// Red channel, 0-255.
  var colorRed: Int64
  /// Green channel, 0-255.
  var colorGreen: Int64
  /// Blue channel, 0-255.
  var colorBlue: Int64
  /// Alpha opacity, 0.0-1.0.
  var opacity: Double
  /// Stroke width in physical pixels.
  var width: Double
  /// Whether the native renderer should split the line into dash segments.
  var dashed: Bool
  /// Dash length in physical pixels when [dashed] is true.
  var dashLength: Double
  /// Gap length in physical pixels when [dashed] is true.
  var gapLength: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DrapeInteractionLineStyle? {
    let colorRed = pigeonVar_list[0] as! Int64
    let colorGreen = pigeonVar_list[1] as! Int64
    let colorBlue = pigeonVar_list[2] as! Int64
    let opacity = pigeonVar_list[3] as! Double
    let width = pigeonVar_list[4] as! Double
    let dashed = pigeonVar_list[5] as! Bool
    let dashLength = pigeonVar_list[6] as! Double
    let gapLength = pigeonVar_list[7] as! Double

    return DrapeInteractionLineStyle(
      colorRed: colorRed,
      colorGreen: colorGreen,
      colorBlue: colorBlue,
      opacity: opacity,
      width: width,
      dashed: dashed,
      dashLength: dashLength,
      gapLength: gapLength
    )
  }
  func toList() -> [Any?] {
    return [
      colorRed,
      colorGreen,
      colorBlue,
      opacity,
      width,
      dashed,
      dashLength,
      gapLength,
    ]
  }
  static func == (lhs: DrapeInteractionLineStyle, rhs: DrapeInteractionLineStyle) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.colorRed, rhs.colorRed) && deepEqualsAgusMapsApi(lhs.colorGreen, rhs.colorGreen) && deepEqualsAgusMapsApi(lhs.colorBlue, rhs.colorBlue) && deepEqualsAgusMapsApi(lhs.opacity, rhs.opacity) && deepEqualsAgusMapsApi(lhs.width, rhs.width) && deepEqualsAgusMapsApi(lhs.dashed, rhs.dashed) && deepEqualsAgusMapsApi(lhs.dashLength, rhs.dashLength) && deepEqualsAgusMapsApi(lhs.gapLength, rhs.gapLength)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DrapeInteractionLineStyle")
    deepHashAgusMapsApi(value: colorRed, hasher: &hasher)
    deepHashAgusMapsApi(value: colorGreen, hasher: &hasher)
    deepHashAgusMapsApi(value: colorBlue, hasher: &hasher)
    deepHashAgusMapsApi(value: opacity, hasher: &hasher)
    deepHashAgusMapsApi(value: width, hasher: &hasher)
    deepHashAgusMapsApi(value: dashed, hasher: &hasher)
    deepHashAgusMapsApi(value: dashLength, hasher: &hasher)
    deepHashAgusMapsApi(value: gapLength, hasher: &hasher)
  }
}

/// Native interaction geometry payload.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DrapeInteractionGeometryRequest: Hashable {
  /// 0 inactive, 1 drawing, 2 editing feature.
  var mode: Int64
  /// WKT geometry, or null to clear.
  var geometryWkt: String? = nil
  /// Style for line/edge geometry.
  var lineStyle: DrapeInteractionLineStyle


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DrapeInteractionGeometryRequest? {
    let mode = pigeonVar_list[0] as! Int64
    let geometryWkt: String? = nilOrValue(pigeonVar_list[1])
    let lineStyle = pigeonVar_list[2] as! DrapeInteractionLineStyle

    return DrapeInteractionGeometryRequest(
      mode: mode,
      geometryWkt: geometryWkt,
      lineStyle: lineStyle
    )
  }
  func toList() -> [Any?] {
    return [
      mode,
      geometryWkt,
      lineStyle,
    ]
  }
  static func == (lhs: DrapeInteractionGeometryRequest, rhs: DrapeInteractionGeometryRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.mode, rhs.mode) && deepEqualsAgusMapsApi(lhs.geometryWkt, rhs.geometryWkt) && deepEqualsAgusMapsApi(lhs.lineStyle, rhs.lineStyle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DrapeInteractionGeometryRequest")
    deepHashAgusMapsApi(value: mode, hasher: &hasher)
    deepHashAgusMapsApi(value: geometryWkt, hasher: &hasher)
    deepHashAgusMapsApi(value: lineStyle, hasher: &hasher)
  }
}

/// Stable identifier for a place page feature.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlacePageFeatureId: Hashable {
  var mwmName: String
  var mwmVersion: Int64
  var index: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlacePageFeatureId? {
    let mwmName = pigeonVar_list[0] as! String
    let mwmVersion = pigeonVar_list[1] as! Int64
    let index = pigeonVar_list[2] as! Int64

    return PlacePageFeatureId(
      mwmName: mwmName,
      mwmVersion: mwmVersion,
      index: index
    )
  }
  func toList() -> [Any?] {
    return [
      mwmName,
      mwmVersion,
      index,
    ]
  }
  static func == (lhs: PlacePageFeatureId, rhs: PlacePageFeatureId) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.mwmName, rhs.mwmName) && deepEqualsAgusMapsApi(lhs.mwmVersion, rhs.mwmVersion) && deepEqualsAgusMapsApi(lhs.index, rhs.index)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlacePageFeatureId")
    deepHashAgusMapsApi(value: mwmName, hasher: &hasher)
    deepHashAgusMapsApi(value: mwmVersion, hasher: &hasher)
    deepHashAgusMapsApi(value: index, hasher: &hasher)
  }
}

/// Formatted coordinates variants for a place page.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlacePageCoordinates: Hashable {
  var decimal: String? = nil
  var dms: String? = nil
  var osm: String? = nil
  var olc: String? = nil
  var utm: String? = nil
  var mgrs: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlacePageCoordinates? {
    let decimal: String? = nilOrValue(pigeonVar_list[0])
    let dms: String? = nilOrValue(pigeonVar_list[1])
    let osm: String? = nilOrValue(pigeonVar_list[2])
    let olc: String? = nilOrValue(pigeonVar_list[3])
    let utm: String? = nilOrValue(pigeonVar_list[4])
    let mgrs: String? = nilOrValue(pigeonVar_list[5])

    return PlacePageCoordinates(
      decimal: decimal,
      dms: dms,
      osm: osm,
      olc: olc,
      utm: utm,
      mgrs: mgrs
    )
  }
  func toList() -> [Any?] {
    return [
      decimal,
      dms,
      osm,
      olc,
      utm,
      mgrs,
    ]
  }
  static func == (lhs: PlacePageCoordinates, rhs: PlacePageCoordinates) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.decimal, rhs.decimal) && deepEqualsAgusMapsApi(lhs.dms, rhs.dms) && deepEqualsAgusMapsApi(lhs.osm, rhs.osm) && deepEqualsAgusMapsApi(lhs.olc, rhs.olc) && deepEqualsAgusMapsApi(lhs.utm, rhs.utm) && deepEqualsAgusMapsApi(lhs.mgrs, rhs.mgrs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlacePageCoordinates")
    deepHashAgusMapsApi(value: decimal, hasher: &hasher)
    deepHashAgusMapsApi(value: dms, hasher: &hasher)
    deepHashAgusMapsApi(value: osm, hasher: &hasher)
    deepHashAgusMapsApi(value: olc, hasher: &hasher)
    deepHashAgusMapsApi(value: utm, hasher: &hasher)
    deepHashAgusMapsApi(value: mgrs, hasher: &hasher)
  }
}

/// Integer-keyed metadata entry.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlacePageIntMetadataEntry: Hashable {
  var key: Int64
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlacePageIntMetadataEntry? {
    let key = pigeonVar_list[0] as! Int64
    let value = pigeonVar_list[1] as! String

    return PlacePageIntMetadataEntry(
      key: key,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      value,
    ]
  }
  static func == (lhs: PlacePageIntMetadataEntry, rhs: PlacePageIntMetadataEntry) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.key, rhs.key) && deepEqualsAgusMapsApi(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlacePageIntMetadataEntry")
    deepHashAgusMapsApi(value: key, hasher: &hasher)
    deepHashAgusMapsApi(value: value, hasher: &hasher)
  }
}

/// String-keyed metadata entry.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlacePageStringMetadataEntry: Hashable {
  var key: String
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlacePageStringMetadataEntry? {
    let key = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! String

    return PlacePageStringMetadataEntry(
      key: key,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      value,
    ]
  }
  static func == (lhs: PlacePageStringMetadataEntry, rhs: PlacePageStringMetadataEntry) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.key, rhs.key) && deepEqualsAgusMapsApi(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlacePageStringMetadataEntry")
    deepHashAgusMapsApi(value: key, hasher: &hasher)
    deepHashAgusMapsApi(value: value, hasher: &hasher)
  }
}

/// Structured place page payload.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlacePageData: Hashable {
  var featureId: PlacePageFeatureId
  var objectType: Int64
  var openingMode: Int64
  var title: String
  var secondaryTitle: String
  var subtitle: String
  var address: String
  var lat: Double
  var lon: Double
  var wikiDescriptionHtml: String
  var roadType: Int64
  var isRoutePoint: Bool
  var coordinates: PlacePageCoordinates
  var rawTypes: [String]
  var metadata: [PlacePageIntMetadataEntry]
  var metadataTags: [PlacePageStringMetadataEntry]
  var bookmarkId: Int64? = nil
  var bookmarkCategoryId: Int64? = nil
  var trackId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlacePageData? {
    let featureId = pigeonVar_list[0] as! PlacePageFeatureId
    let objectType = pigeonVar_list[1] as! Int64
    let openingMode = pigeonVar_list[2] as! Int64
    let title = pigeonVar_list[3] as! String
    let secondaryTitle = pigeonVar_list[4] as! String
    let subtitle = pigeonVar_list[5] as! String
    let address = pigeonVar_list[6] as! String
    let lat = pigeonVar_list[7] as! Double
    let lon = pigeonVar_list[8] as! Double
    let wikiDescriptionHtml = pigeonVar_list[9] as! String
    let roadType = pigeonVar_list[10] as! Int64
    let isRoutePoint = pigeonVar_list[11] as! Bool
    let coordinates = pigeonVar_list[12] as! PlacePageCoordinates
    let rawTypes = pigeonVar_list[13] as! [String]
    let metadata = pigeonVar_list[14] as! [PlacePageIntMetadataEntry]
    let metadataTags = pigeonVar_list[15] as! [PlacePageStringMetadataEntry]
    let bookmarkId: Int64? = nilOrValue(pigeonVar_list[16])
    let bookmarkCategoryId: Int64? = nilOrValue(pigeonVar_list[17])
    let trackId: Int64? = nilOrValue(pigeonVar_list[18])

    return PlacePageData(
      featureId: featureId,
      objectType: objectType,
      openingMode: openingMode,
      title: title,
      secondaryTitle: secondaryTitle,
      subtitle: subtitle,
      address: address,
      lat: lat,
      lon: lon,
      wikiDescriptionHtml: wikiDescriptionHtml,
      roadType: roadType,
      isRoutePoint: isRoutePoint,
      coordinates: coordinates,
      rawTypes: rawTypes,
      metadata: metadata,
      metadataTags: metadataTags,
      bookmarkId: bookmarkId,
      bookmarkCategoryId: bookmarkCategoryId,
      trackId: trackId
    )
  }
  func toList() -> [Any?] {
    return [
      featureId,
      objectType,
      openingMode,
      title,
      secondaryTitle,
      subtitle,
      address,
      lat,
      lon,
      wikiDescriptionHtml,
      roadType,
      isRoutePoint,
      coordinates,
      rawTypes,
      metadata,
      metadataTags,
      bookmarkId,
      bookmarkCategoryId,
      trackId,
    ]
  }
  static func == (lhs: PlacePageData, rhs: PlacePageData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgusMapsApi(lhs.featureId, rhs.featureId) && deepEqualsAgusMapsApi(lhs.objectType, rhs.objectType) && deepEqualsAgusMapsApi(lhs.openingMode, rhs.openingMode) && deepEqualsAgusMapsApi(lhs.title, rhs.title) && deepEqualsAgusMapsApi(lhs.secondaryTitle, rhs.secondaryTitle) && deepEqualsAgusMapsApi(lhs.subtitle, rhs.subtitle) && deepEqualsAgusMapsApi(lhs.address, rhs.address) && deepEqualsAgusMapsApi(lhs.lat, rhs.lat) && deepEqualsAgusMapsApi(lhs.lon, rhs.lon) && deepEqualsAgusMapsApi(lhs.wikiDescriptionHtml, rhs.wikiDescriptionHtml) && deepEqualsAgusMapsApi(lhs.roadType, rhs.roadType) && deepEqualsAgusMapsApi(lhs.isRoutePoint, rhs.isRoutePoint) && deepEqualsAgusMapsApi(lhs.coordinates, rhs.coordinates) && deepEqualsAgusMapsApi(lhs.rawTypes, rhs.rawTypes) && deepEqualsAgusMapsApi(lhs.metadata, rhs.metadata) && deepEqualsAgusMapsApi(lhs.metadataTags, rhs.metadataTags) && deepEqualsAgusMapsApi(lhs.bookmarkId, rhs.bookmarkId) && deepEqualsAgusMapsApi(lhs.bookmarkCategoryId, rhs.bookmarkCategoryId) && deepEqualsAgusMapsApi(lhs.trackId, rhs.trackId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlacePageData")
    deepHashAgusMapsApi(value: featureId, hasher: &hasher)
    deepHashAgusMapsApi(value: objectType, hasher: &hasher)
    deepHashAgusMapsApi(value: openingMode, hasher: &hasher)
    deepHashAgusMapsApi(value: title, hasher: &hasher)
    deepHashAgusMapsApi(value: secondaryTitle, hasher: &hasher)
    deepHashAgusMapsApi(value: subtitle, hasher: &hasher)
    deepHashAgusMapsApi(value: address, hasher: &hasher)
    deepHashAgusMapsApi(value: lat, hasher: &hasher)
    deepHashAgusMapsApi(value: lon, hasher: &hasher)
    deepHashAgusMapsApi(value: wikiDescriptionHtml, hasher: &hasher)
    deepHashAgusMapsApi(value: roadType, hasher: &hasher)
    deepHashAgusMapsApi(value: isRoutePoint, hasher: &hasher)
    deepHashAgusMapsApi(value: coordinates, hasher: &hasher)
    deepHashAgusMapsApi(value: rawTypes, hasher: &hasher)
    deepHashAgusMapsApi(value: metadata, hasher: &hasher)
    deepHashAgusMapsApi(value: metadataTags, hasher: &hasher)
    deepHashAgusMapsApi(value: bookmarkId, hasher: &hasher)
    deepHashAgusMapsApi(value: bookmarkCategoryId, hasher: &hasher)
    deepHashAgusMapsApi(value: trackId, hasher: &hasher)
  }
}

private class AgusMapsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RenderState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CreateMapSurfaceRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return ResizeMapSurfaceRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return MapPointerUpdateRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return MapPointerCoordinate.fromList(self.readValue() as! [Any?])
    case 134:
      return DrapeInteractionLineStyle.fromList(self.readValue() as! [Any?])
    case 135:
      return DrapeInteractionGeometryRequest.fromList(self.readValue() as! [Any?])
    case 136:
      return PlacePageFeatureId.fromList(self.readValue() as! [Any?])
    case 137:
      return PlacePageCoordinates.fromList(self.readValue() as! [Any?])
    case 138:
      return PlacePageIntMetadataEntry.fromList(self.readValue() as! [Any?])
    case 139:
      return PlacePageStringMetadataEntry.fromList(self.readValue() as! [Any?])
    case 140:
      return PlacePageData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AgusMapsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RenderState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CreateMapSurfaceRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ResizeMapSurfaceRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MapPointerUpdateRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MapPointerCoordinate {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? DrapeInteractionLineStyle {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? DrapeInteractionGeometryRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PlacePageFeatureId {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PlacePageCoordinates {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PlacePageIntMetadataEntry {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PlacePageStringMetadataEntry {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PlacePageData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AgusMapsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AgusMapsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AgusMapsApiPigeonCodecWriter(data: data)
  }
}

class AgusMapsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AgusMapsApiPigeonCodec(readerWriter: AgusMapsApiPigeonCodecReaderWriter())
}


/// Host API implemented by native platforms.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AgusMapsHostApi {
  func extractMap(assetPath: String, completion: @escaping (Result<String, Error>) -> Void)
  func extractDataFiles(completion: @escaping (Result<String, Error>) -> Void)
  func getApkPath(completion: @escaping (Result<String, Error>) -> Void)
  func createMapSurface(request: CreateMapSurfaceRequest, completion: @escaping (Result<Int64, Error>) -> Void)
  func resizeMapSurface(request: ResizeMapSurfaceRequest, completion: @escaping (Result<Bool, Error>) -> Void)
  func destroyMapSurface(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Updates the native global pointer tracker and returns the projected map
  /// coordinate when the pointer is inside a ready map surface.
  func updateMapPointer(request: MapPointerUpdateRequest, completion: @escaping (Result<MapPointerCoordinate?, Error>) -> Void)
  /// Updates native draw/edit interaction geometry with caller-provided styling.
  func updateDrapeInteractionGeometry(request: DrapeInteractionGeometryRequest, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns the current place page payload if available.
  func getCurrentPlacePage(completion: @escaping (Result<PlacePageData?, Error>) -> Void)
  /// Clears the active place page selection.
  func clearPlacePageSelection(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AgusMapsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AgusMapsApiPigeonCodec.shared }
  /// Sets up an instance of `AgusMapsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AgusMapsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let extractMapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractMap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      extractMapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetPathArg = args[0] as! String
        api.extractMap(assetPath: assetPathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      extractMapChannel.setMessageHandler(nil)
    }
    let extractDataFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractDataFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      extractDataFilesChannel.setMessageHandler { _, reply in
        api.extractDataFiles { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      extractDataFilesChannel.setMessageHandler(nil)
    }
    let getApkPathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getApkPath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getApkPathChannel.setMessageHandler { _, reply in
        api.getApkPath { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getApkPathChannel.setMessageHandler(nil)
    }
    let createMapSurfaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.createMapSurface\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createMapSurfaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CreateMapSurfaceRequest
        api.createMapSurface(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createMapSurfaceChannel.setMessageHandler(nil)
    }
    let resizeMapSurfaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.resizeMapSurface\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resizeMapSurfaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ResizeMapSurfaceRequest
        api.resizeMapSurface(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resizeMapSurfaceChannel.setMessageHandler(nil)
    }
    let destroyMapSurfaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.destroyMapSurface\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyMapSurfaceChannel.setMessageHandler { _, reply in
        api.destroyMapSurface { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      destroyMapSurfaceChannel.setMessageHandler(nil)
    }
    /// Updates the native global pointer tracker and returns the projected map
    /// coordinate when the pointer is inside a ready map surface.
    let updateMapPointerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.updateMapPointer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateMapPointerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! MapPointerUpdateRequest
        api.updateMapPointer(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateMapPointerChannel.setMessageHandler(nil)
    }
    /// Updates native draw/edit interaction geometry with caller-provided styling.
    let updateDrapeInteractionGeometryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.updateDrapeInteractionGeometry\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateDrapeInteractionGeometryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DrapeInteractionGeometryRequest
        api.updateDrapeInteractionGeometry(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateDrapeInteractionGeometryChannel.setMessageHandler(nil)
    }
    /// Returns the current place page payload if available.
    let getCurrentPlacePageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getCurrentPlacePage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentPlacePageChannel.setMessageHandler { _, reply in
        api.getCurrentPlacePage { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCurrentPlacePageChannel.setMessageHandler(nil)
    }
    /// Clears the active place page selection.
    let clearPlacePageSelectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.clearPlacePageSelection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearPlacePageSelectionChannel.setMessageHandler { _, reply in
        api.clearPlacePageSelection { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearPlacePageSelectionChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API implemented by Dart for low-frequency notifications.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AgusMapsFlutterApiProtocol {
  func onMapReady(surfaceId surfaceIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRenderStateChanged(state stateArg: RenderState, surfaceId surfaceIdArg: Int64?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPlacePageChanged(placePage placePageArg: PlacePageData?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AgusMapsFlutterApi: AgusMapsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AgusMapsApiPigeonCodec {
    return AgusMapsApiPigeonCodec.shared
  }
  func onMapReady(surfaceId surfaceIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onMapReady\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([surfaceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRenderStateChanged(state stateArg: RenderState, surfaceId surfaceIdArg: Int64?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onRenderStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg, surfaceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPlacePageChanged(placePage placePageArg: PlacePageData?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onPlacePageChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([placePageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
