// Generates the C++ DuckDB migration manifest from reviewable SQL files.

import 'dart:io';

import 'package:path/path.dart' as path;

import 'platform_detector.dart' show getRepoRoot;

final RegExp _migrationFilePattern =
    RegExp(r'^(\d{8}_\d{3})_([a-z0-9_]+)\.sql$');
final RegExp _descriptionPattern = RegExp(
  r'^--\s*agus_migration_description:\s*(.+)\r?\n(\r?\n)?',
);

class DuckDBMigrationSource {
  const DuckDBMigrationSource({
    required this.version,
    required this.description,
    required this.sql,
  });

  final String version;
  final String description;
  final String sql;
}

Future<bool> generateDuckDBMigrations({bool checkOnly = false}) async {
  final repoRoot = getRepoRoot();
  final migrationsDir = Directory(
    path.join(repoRoot, 'doc', 'schemas', 'migrations'),
  );
  final outputFile = File(
    path.join(repoRoot, 'src', 'agus_duckdb_migrations.inc'),
  );

  if (!await migrationsDir.exists()) {
    throw Exception(
        'DuckDB migrations directory not found: ${migrationsDir.path}');
  }

  final migrations = await _loadMigrations(migrationsDir);
  if (migrations.isEmpty) {
    throw Exception(
        'No DuckDB migration SQL files found in ${migrationsDir.path}');
  }

  final generated = _renderMigrationInclude(migrations);

  if (checkOnly) {
    final current =
        await outputFile.exists() ? await outputFile.readAsString() : '';
    if (current != generated) {
      stderr.writeln('DuckDB migration manifest is stale.');
      stderr.writeln(
        'Run: dart run tool/build.dart --generate-duckdb-migrations',
      );
      return false;
    }
    stdout.writeln('DuckDB migration manifest is up to date');
    return true;
  }

  await outputFile.parent.create(recursive: true);
  await outputFile.writeAsString(generated);
  stdout.writeln(
    'Generated ${path.relative(outputFile.path, from: repoRoot)} '
    'from ${migrations.length} migration(s)',
  );
  return true;
}

Future<List<DuckDBMigrationSource>> _loadMigrations(
    Directory migrationsDir) async {
  final files = await migrationsDir
      .list()
      .where(
          (entity) => entity is File && path.extension(entity.path) == '.sql')
      .cast<File>()
      .toList();

  files.sort((left, right) =>
      path.basename(left.path).compareTo(path.basename(right.path)));

  final migrations = <DuckDBMigrationSource>[];
  for (final file in files) {
    final fileName = path.basename(file.path);
    final match = _migrationFilePattern.firstMatch(fileName);
    if (match == null) {
      throw Exception(
        'DuckDB migration file name must match YYYYMMDD_NNN_slug.sql: $fileName',
      );
    }

    final content = await file.readAsString();
    final version = path.basenameWithoutExtension(fileName);
    final slug = match.group(2)!;
    final (description, sql) = _extractDescription(slug, content, fileName);

    if (sql.contains(')AGUS_SQL"')) {
      throw Exception(
        'DuckDB migration contains the generated raw-string delimiter: $fileName',
      );
    }

    migrations.add(
      DuckDBMigrationSource(
        version: version,
        description: description,
        sql: sql,
      ),
    );
  }

  return migrations;
}

(String, String) _extractDescription(
  String slug,
  String content,
  String fileName,
) {
  final descriptionMatch = _descriptionPattern.firstMatch(content);
  if (descriptionMatch == null) {
    return (_descriptionFromSlug(slug), content);
  }

  final description = descriptionMatch.group(1)!.trim();
  if (description.isEmpty) {
    throw Exception('DuckDB migration description is empty: $fileName');
  }

  return (description, content.substring(descriptionMatch.end));
}

String _descriptionFromSlug(String slug) => slug
    .split('_')
    .where((word) => word.isNotEmpty)
    .map(_titleCaseMigrationWord)
    .join(' ');

String _titleCaseMigrationWord(String word) {
  switch (word) {
    case 'duckdb':
      return 'DuckDB';
    case 'mwm':
      return 'MWM';
    case 'sql':
      return 'SQL';
    default:
      return word.substring(0, 1).toUpperCase() + word.substring(1);
  }
}

String _renderMigrationInclude(List<DuckDBMigrationSource> migrations) {
  final buffer = StringBuffer()
    ..writeln(
        '// Generated by tool/generate_duckdb_migrations.dart. Do not edit.')
    ..writeln('// Source: doc/schemas/migrations/*.sql')
    ..writeln();

  for (final migration in migrations) {
    buffer
      ..writeln(
          'char const ${_migrationSqlIdentifier(migration.version)}[] = R"AGUS_SQL(${migration.sql})AGUS_SQL";')
      ..writeln();
  }

  buffer.writeln('DuckDBMigration const kDuckDBMigrations[] = {');
  for (final migration in migrations) {
    buffer
      ..writeln('    {')
      ..writeln('        ${_cppString(migration.version)},')
      ..writeln('        ${_cppString(migration.description)},')
      ..writeln('        ${_migrationSqlIdentifier(migration.version)},')
      ..writeln('    },');
  }
  buffer.writeln('};');

  return buffer.toString();
}

String _migrationSqlIdentifier(String version) {
  final parts = version
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((part) => part.isNotEmpty)
      .map(_upperCamelIdentifierPart)
      .join();
  return 'kDuckDBMigration${parts}Sql';
}

String _upperCamelIdentifierPart(String value) {
  switch (value.toLowerCase()) {
    case 'duckdb':
      return 'DuckDB';
    case 'mwm':
      return 'MWM';
    case 'sql':
      return 'SQL';
  }

  if (value.isEmpty) {
    return value;
  }
  return value.substring(0, 1).toUpperCase() + value.substring(1);
}

String _cppString(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll('"', r'\"')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\t', r'\t');
  return '"$escaped"';
}
