// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package app.agus.maps.agus_maps_flutter;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class AgusMapsApi {
  static boolean pigeonDoubleEquals(double a, double b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0 ? 0.0 : a) == (b == 0.0 ? 0.0 : b) || (Double.isNaN(a) && Double.isNaN(b));
  }

  static boolean pigeonFloatEquals(float a, float b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0f ? 0.0f : a) == (b == 0.0f ? 0.0f : b) || (Float.isNaN(a) && Float.isNaN(b));
  }

  static int pigeonDoubleHashCode(double d) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (d == 0.0) {
      d = 0.0;
    }
    long bits = Double.doubleToLongBits(d);
    return (int) (bits ^ (bits >>> 32));
  }

  static int pigeonFloatHashCode(float f) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (f == 0.0f) {
      f = 0.0f;
    }
    return Float.floatToIntBits(f);
  }

  static boolean pigeonDeepEquals(Object a, Object b) {
    if (a == b) { return true; }
    if (a == null || b == null) { return false; }
    if (a instanceof byte[] && b instanceof byte[]) {
      return Arrays.equals((byte[]) a, (byte[]) b);
    }
    if (a instanceof int[] && b instanceof int[]) {
      return Arrays.equals((int[]) a, (int[]) b);
    }
    if (a instanceof long[] && b instanceof long[]) {
      return Arrays.equals((long[]) a, (long[]) b);
    }
    if (a instanceof double[] && b instanceof double[]) {
      double[] da = (double[]) a;
      double[] db = (double[]) b;
      if (da.length != db.length) {
        return false;
      }
      for (int i = 0; i < da.length; i++) {
        if (!pigeonDoubleEquals(da[i], db[i])) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof List && b instanceof List) {
      List<?> listA = (List<?>) a;
      List<?> listB = (List<?>) b;
      if (listA.size() != listB.size()) { return false; }
      for (int i = 0; i < listA.size(); i++) {
        if (!pigeonDeepEquals(listA.get(i), listB.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Map && b instanceof Map) {
      Map<?, ?> mapA = (Map<?, ?>) a;
      Map<?, ?> mapB = (Map<?, ?>) b;
      if (mapA.size() != mapB.size()) { return false; }
      for (Map.Entry<?, ?> entryA : mapA.entrySet()) {
        Object keyA = entryA.getKey();
        Object valueA = entryA.getValue();
        boolean found = false;
        for (Map.Entry<?, ?> entryB : mapB.entrySet()) {
          Object keyB = entryB.getKey();
          if (pigeonDeepEquals(keyA, keyB)) {
            Object valueB = entryB.getValue();
            if (pigeonDeepEquals(valueA, valueB)) {
              found = true;
              break;
            } else {
              return false;
            }
          }
        }
        if (!found) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Double && b instanceof Double) {
      return pigeonDoubleEquals((double) a, (double) b);
    }
    if (a instanceof Float && b instanceof Float) {
      return pigeonFloatEquals((float) a, (float) b);
    }
    return a.equals(b);
  }

  static int pigeonDeepHashCode(Object value) {
    if (value == null) { return 0; }
    if (value instanceof byte[]) {
      return Arrays.hashCode((byte[]) value);
    }
    if (value instanceof int[]) {
      return Arrays.hashCode((int[]) value);
    }
    if (value instanceof long[]) {
      return Arrays.hashCode((long[]) value);
    }
    if (value instanceof double[]) {
      double[] da = (double[]) value;
      int result = 1;
      for (double d : da) {
        result = 31 * result + pigeonDoubleHashCode(d);
      }
      return result;
    }
    if (value instanceof List) {
      int result = 1;
      for (Object item : (List<?>) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Map) {
      int result = 0;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        result += ((pigeonDeepHashCode(entry.getKey()) * 31) ^ pigeonDeepHashCode(entry.getValue()));
      }
      return result;
    }
    if (value instanceof Object[]) {
      int result = 1;
      for (Object item : (Object[]) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Double) {
      return pigeonDoubleHashCode((double) value);
    }
    if (value instanceof Float) {
      return pigeonFloatHashCode((float) value);
    }
    return value.hashCode();
  }


  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @NonNull
  protected static FlutterError createConnectionError(@NonNull String channelName) {
    return new FlutterError("channel-error",  "Unable to establish connection on channel: " + channelName + ".", "");
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Rendering activity state for low-frequency notifications. */
  public enum RenderState {
    /** Rendering is active (frames expected). */
    ACTIVE(0),
    /** Rendering is idle (no frames expected). */
    IDLE(1);

    final int index;

    RenderState(final int index) {
      this.index = index;
    }
  }

  /**
   * Request payload for creating a map surface.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class CreateMapSurfaceRequest {
    private @Nullable Long width;

    public @Nullable Long getWidth() {
      return width;
    }

    public void setWidth(@Nullable Long setterArg) {
      this.width = setterArg;
    }

    private @Nullable Long height;

    public @Nullable Long getHeight() {
      return height;
    }

    public void setHeight(@Nullable Long setterArg) {
      this.height = setterArg;
    }

    private @Nullable Double density;

    public @Nullable Double getDensity() {
      return density;
    }

    public void setDensity(@Nullable Double setterArg) {
      this.density = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      CreateMapSurfaceRequest that = (CreateMapSurfaceRequest) o;
      return pigeonDeepEquals(width, that.width) && pigeonDeepEquals(height, that.height) && pigeonDeepEquals(density, that.density);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), width, height, density};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Long width;

      @CanIgnoreReturnValue
      public @NonNull Builder setWidth(@Nullable Long setterArg) {
        this.width = setterArg;
        return this;
      }

      private @Nullable Long height;

      @CanIgnoreReturnValue
      public @NonNull Builder setHeight(@Nullable Long setterArg) {
        this.height = setterArg;
        return this;
      }

      private @Nullable Double density;

      @CanIgnoreReturnValue
      public @NonNull Builder setDensity(@Nullable Double setterArg) {
        this.density = setterArg;
        return this;
      }

      public @NonNull CreateMapSurfaceRequest build() {
        CreateMapSurfaceRequest pigeonReturn = new CreateMapSurfaceRequest();
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        pigeonReturn.setDensity(density);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(width);
      toListResult.add(height);
      toListResult.add(density);
      return toListResult;
    }

    static @NonNull CreateMapSurfaceRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      CreateMapSurfaceRequest pigeonResult = new CreateMapSurfaceRequest();
      Object width = pigeonVar_list.get(0);
      pigeonResult.setWidth((Long) width);
      Object height = pigeonVar_list.get(1);
      pigeonResult.setHeight((Long) height);
      Object density = pigeonVar_list.get(2);
      pigeonResult.setDensity((Double) density);
      return pigeonResult;
    }
  }

  /**
   * Request payload for resizing a map surface.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class ResizeMapSurfaceRequest {
    private @NonNull Long width;

    public @NonNull Long getWidth() {
      return width;
    }

    public void setWidth(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"width\" is null.");
      }
      this.width = setterArg;
    }

    private @NonNull Long height;

    public @NonNull Long getHeight() {
      return height;
    }

    public void setHeight(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"height\" is null.");
      }
      this.height = setterArg;
    }

    private @Nullable Double density;

    public @Nullable Double getDensity() {
      return density;
    }

    public void setDensity(@Nullable Double setterArg) {
      this.density = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ResizeMapSurfaceRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ResizeMapSurfaceRequest that = (ResizeMapSurfaceRequest) o;
      return pigeonDeepEquals(width, that.width) && pigeonDeepEquals(height, that.height) && pigeonDeepEquals(density, that.density);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), width, height, density};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Long width;

      @CanIgnoreReturnValue
      public @NonNull Builder setWidth(@NonNull Long setterArg) {
        this.width = setterArg;
        return this;
      }

      private @Nullable Long height;

      @CanIgnoreReturnValue
      public @NonNull Builder setHeight(@NonNull Long setterArg) {
        this.height = setterArg;
        return this;
      }

      private @Nullable Double density;

      @CanIgnoreReturnValue
      public @NonNull Builder setDensity(@Nullable Double setterArg) {
        this.density = setterArg;
        return this;
      }

      public @NonNull ResizeMapSurfaceRequest build() {
        ResizeMapSurfaceRequest pigeonReturn = new ResizeMapSurfaceRequest();
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        pigeonReturn.setDensity(density);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(width);
      toListResult.add(height);
      toListResult.add(density);
      return toListResult;
    }

    static @NonNull ResizeMapSurfaceRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ResizeMapSurfaceRequest pigeonResult = new ResizeMapSurfaceRequest();
      Object width = pigeonVar_list.get(0);
      pigeonResult.setWidth((Long) width);
      Object height = pigeonVar_list.get(1);
      pigeonResult.setHeight((Long) height);
      Object density = pigeonVar_list.get(2);
      pigeonResult.setDensity((Double) density);
      return pigeonResult;
    }
  }

  /**
   * Pointer position in the native map surface's physical pixel space.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class MapPointerUpdateRequest {
    private @NonNull Double physicalX;

    public @NonNull Double getPhysicalX() {
      return physicalX;
    }

    public void setPhysicalX(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"physicalX\" is null.");
      }
      this.physicalX = setterArg;
    }

    private @NonNull Double physicalY;

    public @NonNull Double getPhysicalY() {
      return physicalY;
    }

    public void setPhysicalY(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"physicalY\" is null.");
      }
      this.physicalY = setterArg;
    }

    private @NonNull Boolean insideMap;

    public @NonNull Boolean getInsideMap() {
      return insideMap;
    }

    public void setInsideMap(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"insideMap\" is null.");
      }
      this.insideMap = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    MapPointerUpdateRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      MapPointerUpdateRequest that = (MapPointerUpdateRequest) o;
      return pigeonDeepEquals(physicalX, that.physicalX) && pigeonDeepEquals(physicalY, that.physicalY) && pigeonDeepEquals(insideMap, that.insideMap);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), physicalX, physicalY, insideMap};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Double physicalX;

      @CanIgnoreReturnValue
      public @NonNull Builder setPhysicalX(@NonNull Double setterArg) {
        this.physicalX = setterArg;
        return this;
      }

      private @Nullable Double physicalY;

      @CanIgnoreReturnValue
      public @NonNull Builder setPhysicalY(@NonNull Double setterArg) {
        this.physicalY = setterArg;
        return this;
      }

      private @Nullable Boolean insideMap;

      @CanIgnoreReturnValue
      public @NonNull Builder setInsideMap(@NonNull Boolean setterArg) {
        this.insideMap = setterArg;
        return this;
      }

      public @NonNull MapPointerUpdateRequest build() {
        MapPointerUpdateRequest pigeonReturn = new MapPointerUpdateRequest();
        pigeonReturn.setPhysicalX(physicalX);
        pigeonReturn.setPhysicalY(physicalY);
        pigeonReturn.setInsideMap(insideMap);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(physicalX);
      toListResult.add(physicalY);
      toListResult.add(insideMap);
      return toListResult;
    }

    static @NonNull MapPointerUpdateRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      MapPointerUpdateRequest pigeonResult = new MapPointerUpdateRequest();
      Object physicalX = pigeonVar_list.get(0);
      pigeonResult.setPhysicalX((Double) physicalX);
      Object physicalY = pigeonVar_list.get(1);
      pigeonResult.setPhysicalY((Double) physicalY);
      Object insideMap = pigeonVar_list.get(2);
      pigeonResult.setInsideMap((Boolean) insideMap);
      return pigeonResult;
    }
  }

  /**
   * Native map-space pointer projection result.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class MapPointerCoordinate {
    private @NonNull Double physicalX;

    public @NonNull Double getPhysicalX() {
      return physicalX;
    }

    public void setPhysicalX(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"physicalX\" is null.");
      }
      this.physicalX = setterArg;
    }

    private @NonNull Double physicalY;

    public @NonNull Double getPhysicalY() {
      return physicalY;
    }

    public void setPhysicalY(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"physicalY\" is null.");
      }
      this.physicalY = setterArg;
    }

    private @NonNull Boolean insideMap;

    public @NonNull Boolean getInsideMap() {
      return insideMap;
    }

    public void setInsideMap(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"insideMap\" is null.");
      }
      this.insideMap = setterArg;
    }

    private @NonNull Double lat;

    public @NonNull Double getLat() {
      return lat;
    }

    public void setLat(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"lat\" is null.");
      }
      this.lat = setterArg;
    }

    private @NonNull Double lon;

    public @NonNull Double getLon() {
      return lon;
    }

    public void setLon(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"lon\" is null.");
      }
      this.lon = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    MapPointerCoordinate() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      MapPointerCoordinate that = (MapPointerCoordinate) o;
      return pigeonDeepEquals(physicalX, that.physicalX) && pigeonDeepEquals(physicalY, that.physicalY) && pigeonDeepEquals(insideMap, that.insideMap) && pigeonDeepEquals(lat, that.lat) && pigeonDeepEquals(lon, that.lon);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), physicalX, physicalY, insideMap, lat, lon};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Double physicalX;

      @CanIgnoreReturnValue
      public @NonNull Builder setPhysicalX(@NonNull Double setterArg) {
        this.physicalX = setterArg;
        return this;
      }

      private @Nullable Double physicalY;

      @CanIgnoreReturnValue
      public @NonNull Builder setPhysicalY(@NonNull Double setterArg) {
        this.physicalY = setterArg;
        return this;
      }

      private @Nullable Boolean insideMap;

      @CanIgnoreReturnValue
      public @NonNull Builder setInsideMap(@NonNull Boolean setterArg) {
        this.insideMap = setterArg;
        return this;
      }

      private @Nullable Double lat;

      @CanIgnoreReturnValue
      public @NonNull Builder setLat(@NonNull Double setterArg) {
        this.lat = setterArg;
        return this;
      }

      private @Nullable Double lon;

      @CanIgnoreReturnValue
      public @NonNull Builder setLon(@NonNull Double setterArg) {
        this.lon = setterArg;
        return this;
      }

      public @NonNull MapPointerCoordinate build() {
        MapPointerCoordinate pigeonReturn = new MapPointerCoordinate();
        pigeonReturn.setPhysicalX(physicalX);
        pigeonReturn.setPhysicalY(physicalY);
        pigeonReturn.setInsideMap(insideMap);
        pigeonReturn.setLat(lat);
        pigeonReturn.setLon(lon);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(5);
      toListResult.add(physicalX);
      toListResult.add(physicalY);
      toListResult.add(insideMap);
      toListResult.add(lat);
      toListResult.add(lon);
      return toListResult;
    }

    static @NonNull MapPointerCoordinate fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      MapPointerCoordinate pigeonResult = new MapPointerCoordinate();
      Object physicalX = pigeonVar_list.get(0);
      pigeonResult.setPhysicalX((Double) physicalX);
      Object physicalY = pigeonVar_list.get(1);
      pigeonResult.setPhysicalY((Double) physicalY);
      Object insideMap = pigeonVar_list.get(2);
      pigeonResult.setInsideMap((Boolean) insideMap);
      Object lat = pigeonVar_list.get(3);
      pigeonResult.setLat((Double) lat);
      Object lon = pigeonVar_list.get(4);
      pigeonResult.setLon((Double) lon);
      return pigeonResult;
    }
  }

  /**
   * Native interaction line style for transient draw/edit geometry.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class DrapeInteractionLineStyle {
    /** Red channel, 0-255. */
    private @NonNull Long colorRed;

    public @NonNull Long getColorRed() {
      return colorRed;
    }

    public void setColorRed(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"colorRed\" is null.");
      }
      this.colorRed = setterArg;
    }

    /** Green channel, 0-255. */
    private @NonNull Long colorGreen;

    public @NonNull Long getColorGreen() {
      return colorGreen;
    }

    public void setColorGreen(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"colorGreen\" is null.");
      }
      this.colorGreen = setterArg;
    }

    /** Blue channel, 0-255. */
    private @NonNull Long colorBlue;

    public @NonNull Long getColorBlue() {
      return colorBlue;
    }

    public void setColorBlue(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"colorBlue\" is null.");
      }
      this.colorBlue = setterArg;
    }

    /** Alpha opacity, 0.0-1.0. */
    private @NonNull Double opacity;

    public @NonNull Double getOpacity() {
      return opacity;
    }

    public void setOpacity(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"opacity\" is null.");
      }
      this.opacity = setterArg;
    }

    /** Stroke width in physical pixels. */
    private @NonNull Double width;

    public @NonNull Double getWidth() {
      return width;
    }

    public void setWidth(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"width\" is null.");
      }
      this.width = setterArg;
    }

    /** Whether the native renderer should split the line into dash segments. */
    private @NonNull Boolean dashed;

    public @NonNull Boolean getDashed() {
      return dashed;
    }

    public void setDashed(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dashed\" is null.");
      }
      this.dashed = setterArg;
    }

    /** Dash length in physical pixels when [dashed] is true. */
    private @NonNull Double dashLength;

    public @NonNull Double getDashLength() {
      return dashLength;
    }

    public void setDashLength(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dashLength\" is null.");
      }
      this.dashLength = setterArg;
    }

    /** Gap length in physical pixels when [dashed] is true. */
    private @NonNull Double gapLength;

    public @NonNull Double getGapLength() {
      return gapLength;
    }

    public void setGapLength(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"gapLength\" is null.");
      }
      this.gapLength = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DrapeInteractionLineStyle() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      DrapeInteractionLineStyle that = (DrapeInteractionLineStyle) o;
      return pigeonDeepEquals(colorRed, that.colorRed) && pigeonDeepEquals(colorGreen, that.colorGreen) && pigeonDeepEquals(colorBlue, that.colorBlue) && pigeonDeepEquals(opacity, that.opacity) && pigeonDeepEquals(width, that.width) && pigeonDeepEquals(dashed, that.dashed) && pigeonDeepEquals(dashLength, that.dashLength) && pigeonDeepEquals(gapLength, that.gapLength);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), colorRed, colorGreen, colorBlue, opacity, width, dashed, dashLength, gapLength};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Long colorRed;

      @CanIgnoreReturnValue
      public @NonNull Builder setColorRed(@NonNull Long setterArg) {
        this.colorRed = setterArg;
        return this;
      }

      private @Nullable Long colorGreen;

      @CanIgnoreReturnValue
      public @NonNull Builder setColorGreen(@NonNull Long setterArg) {
        this.colorGreen = setterArg;
        return this;
      }

      private @Nullable Long colorBlue;

      @CanIgnoreReturnValue
      public @NonNull Builder setColorBlue(@NonNull Long setterArg) {
        this.colorBlue = setterArg;
        return this;
      }

      private @Nullable Double opacity;

      @CanIgnoreReturnValue
      public @NonNull Builder setOpacity(@NonNull Double setterArg) {
        this.opacity = setterArg;
        return this;
      }

      private @Nullable Double width;

      @CanIgnoreReturnValue
      public @NonNull Builder setWidth(@NonNull Double setterArg) {
        this.width = setterArg;
        return this;
      }

      private @Nullable Boolean dashed;

      @CanIgnoreReturnValue
      public @NonNull Builder setDashed(@NonNull Boolean setterArg) {
        this.dashed = setterArg;
        return this;
      }

      private @Nullable Double dashLength;

      @CanIgnoreReturnValue
      public @NonNull Builder setDashLength(@NonNull Double setterArg) {
        this.dashLength = setterArg;
        return this;
      }

      private @Nullable Double gapLength;

      @CanIgnoreReturnValue
      public @NonNull Builder setGapLength(@NonNull Double setterArg) {
        this.gapLength = setterArg;
        return this;
      }

      public @NonNull DrapeInteractionLineStyle build() {
        DrapeInteractionLineStyle pigeonReturn = new DrapeInteractionLineStyle();
        pigeonReturn.setColorRed(colorRed);
        pigeonReturn.setColorGreen(colorGreen);
        pigeonReturn.setColorBlue(colorBlue);
        pigeonReturn.setOpacity(opacity);
        pigeonReturn.setWidth(width);
        pigeonReturn.setDashed(dashed);
        pigeonReturn.setDashLength(dashLength);
        pigeonReturn.setGapLength(gapLength);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(8);
      toListResult.add(colorRed);
      toListResult.add(colorGreen);
      toListResult.add(colorBlue);
      toListResult.add(opacity);
      toListResult.add(width);
      toListResult.add(dashed);
      toListResult.add(dashLength);
      toListResult.add(gapLength);
      return toListResult;
    }

    static @NonNull DrapeInteractionLineStyle fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DrapeInteractionLineStyle pigeonResult = new DrapeInteractionLineStyle();
      Object colorRed = pigeonVar_list.get(0);
      pigeonResult.setColorRed((Long) colorRed);
      Object colorGreen = pigeonVar_list.get(1);
      pigeonResult.setColorGreen((Long) colorGreen);
      Object colorBlue = pigeonVar_list.get(2);
      pigeonResult.setColorBlue((Long) colorBlue);
      Object opacity = pigeonVar_list.get(3);
      pigeonResult.setOpacity((Double) opacity);
      Object width = pigeonVar_list.get(4);
      pigeonResult.setWidth((Double) width);
      Object dashed = pigeonVar_list.get(5);
      pigeonResult.setDashed((Boolean) dashed);
      Object dashLength = pigeonVar_list.get(6);
      pigeonResult.setDashLength((Double) dashLength);
      Object gapLength = pigeonVar_list.get(7);
      pigeonResult.setGapLength((Double) gapLength);
      return pigeonResult;
    }
  }

  /**
   * Native interaction geometry payload.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class DrapeInteractionGeometryRequest {
    /** 0 inactive, 1 drawing, 2 editing feature. */
    private @NonNull Long mode;

    public @NonNull Long getMode() {
      return mode;
    }

    public void setMode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"mode\" is null.");
      }
      this.mode = setterArg;
    }

    /** WKT geometry, or null to clear. */
    private @Nullable String geometryWkt;

    public @Nullable String getGeometryWkt() {
      return geometryWkt;
    }

    public void setGeometryWkt(@Nullable String setterArg) {
      this.geometryWkt = setterArg;
    }

    /** Style for line/edge geometry. */
    private @NonNull DrapeInteractionLineStyle lineStyle;

    public @NonNull DrapeInteractionLineStyle getLineStyle() {
      return lineStyle;
    }

    public void setLineStyle(@NonNull DrapeInteractionLineStyle setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"lineStyle\" is null.");
      }
      this.lineStyle = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DrapeInteractionGeometryRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      DrapeInteractionGeometryRequest that = (DrapeInteractionGeometryRequest) o;
      return pigeonDeepEquals(mode, that.mode) && pigeonDeepEquals(geometryWkt, that.geometryWkt) && pigeonDeepEquals(lineStyle, that.lineStyle);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), mode, geometryWkt, lineStyle};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Long mode;

      @CanIgnoreReturnValue
      public @NonNull Builder setMode(@NonNull Long setterArg) {
        this.mode = setterArg;
        return this;
      }

      private @Nullable String geometryWkt;

      @CanIgnoreReturnValue
      public @NonNull Builder setGeometryWkt(@Nullable String setterArg) {
        this.geometryWkt = setterArg;
        return this;
      }

      private @Nullable DrapeInteractionLineStyle lineStyle;

      @CanIgnoreReturnValue
      public @NonNull Builder setLineStyle(@NonNull DrapeInteractionLineStyle setterArg) {
        this.lineStyle = setterArg;
        return this;
      }

      public @NonNull DrapeInteractionGeometryRequest build() {
        DrapeInteractionGeometryRequest pigeonReturn = new DrapeInteractionGeometryRequest();
        pigeonReturn.setMode(mode);
        pigeonReturn.setGeometryWkt(geometryWkt);
        pigeonReturn.setLineStyle(lineStyle);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(mode);
      toListResult.add(geometryWkt);
      toListResult.add(lineStyle);
      return toListResult;
    }

    static @NonNull DrapeInteractionGeometryRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DrapeInteractionGeometryRequest pigeonResult = new DrapeInteractionGeometryRequest();
      Object mode = pigeonVar_list.get(0);
      pigeonResult.setMode((Long) mode);
      Object geometryWkt = pigeonVar_list.get(1);
      pigeonResult.setGeometryWkt((String) geometryWkt);
      Object lineStyle = pigeonVar_list.get(2);
      pigeonResult.setLineStyle((DrapeInteractionLineStyle) lineStyle);
      return pigeonResult;
    }
  }

  /**
   * Stable identifier for a place page feature.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PlacePageFeatureId {
    private @NonNull String mwmName;

    public @NonNull String getMwmName() {
      return mwmName;
    }

    public void setMwmName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"mwmName\" is null.");
      }
      this.mwmName = setterArg;
    }

    private @NonNull Long mwmVersion;

    public @NonNull Long getMwmVersion() {
      return mwmVersion;
    }

    public void setMwmVersion(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"mwmVersion\" is null.");
      }
      this.mwmVersion = setterArg;
    }

    private @NonNull Long index;

    public @NonNull Long getIndex() {
      return index;
    }

    public void setIndex(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"index\" is null.");
      }
      this.index = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PlacePageFeatureId() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PlacePageFeatureId that = (PlacePageFeatureId) o;
      return pigeonDeepEquals(mwmName, that.mwmName) && pigeonDeepEquals(mwmVersion, that.mwmVersion) && pigeonDeepEquals(index, that.index);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), mwmName, mwmVersion, index};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String mwmName;

      @CanIgnoreReturnValue
      public @NonNull Builder setMwmName(@NonNull String setterArg) {
        this.mwmName = setterArg;
        return this;
      }

      private @Nullable Long mwmVersion;

      @CanIgnoreReturnValue
      public @NonNull Builder setMwmVersion(@NonNull Long setterArg) {
        this.mwmVersion = setterArg;
        return this;
      }

      private @Nullable Long index;

      @CanIgnoreReturnValue
      public @NonNull Builder setIndex(@NonNull Long setterArg) {
        this.index = setterArg;
        return this;
      }

      public @NonNull PlacePageFeatureId build() {
        PlacePageFeatureId pigeonReturn = new PlacePageFeatureId();
        pigeonReturn.setMwmName(mwmName);
        pigeonReturn.setMwmVersion(mwmVersion);
        pigeonReturn.setIndex(index);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(mwmName);
      toListResult.add(mwmVersion);
      toListResult.add(index);
      return toListResult;
    }

    static @NonNull PlacePageFeatureId fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PlacePageFeatureId pigeonResult = new PlacePageFeatureId();
      Object mwmName = pigeonVar_list.get(0);
      pigeonResult.setMwmName((String) mwmName);
      Object mwmVersion = pigeonVar_list.get(1);
      pigeonResult.setMwmVersion((Long) mwmVersion);
      Object index = pigeonVar_list.get(2);
      pigeonResult.setIndex((Long) index);
      return pigeonResult;
    }
  }

  /**
   * Formatted coordinates variants for a place page.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PlacePageCoordinates {
    private @Nullable String decimal;

    public @Nullable String getDecimal() {
      return decimal;
    }

    public void setDecimal(@Nullable String setterArg) {
      this.decimal = setterArg;
    }

    private @Nullable String dms;

    public @Nullable String getDms() {
      return dms;
    }

    public void setDms(@Nullable String setterArg) {
      this.dms = setterArg;
    }

    private @Nullable String osm;

    public @Nullable String getOsm() {
      return osm;
    }

    public void setOsm(@Nullable String setterArg) {
      this.osm = setterArg;
    }

    private @Nullable String olc;

    public @Nullable String getOlc() {
      return olc;
    }

    public void setOlc(@Nullable String setterArg) {
      this.olc = setterArg;
    }

    private @Nullable String utm;

    public @Nullable String getUtm() {
      return utm;
    }

    public void setUtm(@Nullable String setterArg) {
      this.utm = setterArg;
    }

    private @Nullable String mgrs;

    public @Nullable String getMgrs() {
      return mgrs;
    }

    public void setMgrs(@Nullable String setterArg) {
      this.mgrs = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PlacePageCoordinates that = (PlacePageCoordinates) o;
      return pigeonDeepEquals(decimal, that.decimal) && pigeonDeepEquals(dms, that.dms) && pigeonDeepEquals(osm, that.osm) && pigeonDeepEquals(olc, that.olc) && pigeonDeepEquals(utm, that.utm) && pigeonDeepEquals(mgrs, that.mgrs);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), decimal, dms, osm, olc, utm, mgrs};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String decimal;

      @CanIgnoreReturnValue
      public @NonNull Builder setDecimal(@Nullable String setterArg) {
        this.decimal = setterArg;
        return this;
      }

      private @Nullable String dms;

      @CanIgnoreReturnValue
      public @NonNull Builder setDms(@Nullable String setterArg) {
        this.dms = setterArg;
        return this;
      }

      private @Nullable String osm;

      @CanIgnoreReturnValue
      public @NonNull Builder setOsm(@Nullable String setterArg) {
        this.osm = setterArg;
        return this;
      }

      private @Nullable String olc;

      @CanIgnoreReturnValue
      public @NonNull Builder setOlc(@Nullable String setterArg) {
        this.olc = setterArg;
        return this;
      }

      private @Nullable String utm;

      @CanIgnoreReturnValue
      public @NonNull Builder setUtm(@Nullable String setterArg) {
        this.utm = setterArg;
        return this;
      }

      private @Nullable String mgrs;

      @CanIgnoreReturnValue
      public @NonNull Builder setMgrs(@Nullable String setterArg) {
        this.mgrs = setterArg;
        return this;
      }

      public @NonNull PlacePageCoordinates build() {
        PlacePageCoordinates pigeonReturn = new PlacePageCoordinates();
        pigeonReturn.setDecimal(decimal);
        pigeonReturn.setDms(dms);
        pigeonReturn.setOsm(osm);
        pigeonReturn.setOlc(olc);
        pigeonReturn.setUtm(utm);
        pigeonReturn.setMgrs(mgrs);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(decimal);
      toListResult.add(dms);
      toListResult.add(osm);
      toListResult.add(olc);
      toListResult.add(utm);
      toListResult.add(mgrs);
      return toListResult;
    }

    static @NonNull PlacePageCoordinates fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PlacePageCoordinates pigeonResult = new PlacePageCoordinates();
      Object decimal = pigeonVar_list.get(0);
      pigeonResult.setDecimal((String) decimal);
      Object dms = pigeonVar_list.get(1);
      pigeonResult.setDms((String) dms);
      Object osm = pigeonVar_list.get(2);
      pigeonResult.setOsm((String) osm);
      Object olc = pigeonVar_list.get(3);
      pigeonResult.setOlc((String) olc);
      Object utm = pigeonVar_list.get(4);
      pigeonResult.setUtm((String) utm);
      Object mgrs = pigeonVar_list.get(5);
      pigeonResult.setMgrs((String) mgrs);
      return pigeonResult;
    }
  }

  /**
   * Integer-keyed metadata entry.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PlacePageIntMetadataEntry {
    private @NonNull Long key;

    public @NonNull Long getKey() {
      return key;
    }

    public void setKey(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"key\" is null.");
      }
      this.key = setterArg;
    }

    private @NonNull String value;

    public @NonNull String getValue() {
      return value;
    }

    public void setValue(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"value\" is null.");
      }
      this.value = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PlacePageIntMetadataEntry() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PlacePageIntMetadataEntry that = (PlacePageIntMetadataEntry) o;
      return pigeonDeepEquals(key, that.key) && pigeonDeepEquals(value, that.value);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), key, value};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Long key;

      @CanIgnoreReturnValue
      public @NonNull Builder setKey(@NonNull Long setterArg) {
        this.key = setterArg;
        return this;
      }

      private @Nullable String value;

      @CanIgnoreReturnValue
      public @NonNull Builder setValue(@NonNull String setterArg) {
        this.value = setterArg;
        return this;
      }

      public @NonNull PlacePageIntMetadataEntry build() {
        PlacePageIntMetadataEntry pigeonReturn = new PlacePageIntMetadataEntry();
        pigeonReturn.setKey(key);
        pigeonReturn.setValue(value);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(key);
      toListResult.add(value);
      return toListResult;
    }

    static @NonNull PlacePageIntMetadataEntry fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PlacePageIntMetadataEntry pigeonResult = new PlacePageIntMetadataEntry();
      Object key = pigeonVar_list.get(0);
      pigeonResult.setKey((Long) key);
      Object value = pigeonVar_list.get(1);
      pigeonResult.setValue((String) value);
      return pigeonResult;
    }
  }

  /**
   * String-keyed metadata entry.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PlacePageStringMetadataEntry {
    private @NonNull String key;

    public @NonNull String getKey() {
      return key;
    }

    public void setKey(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"key\" is null.");
      }
      this.key = setterArg;
    }

    private @NonNull String value;

    public @NonNull String getValue() {
      return value;
    }

    public void setValue(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"value\" is null.");
      }
      this.value = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PlacePageStringMetadataEntry() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PlacePageStringMetadataEntry that = (PlacePageStringMetadataEntry) o;
      return pigeonDeepEquals(key, that.key) && pigeonDeepEquals(value, that.value);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), key, value};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String key;

      @CanIgnoreReturnValue
      public @NonNull Builder setKey(@NonNull String setterArg) {
        this.key = setterArg;
        return this;
      }

      private @Nullable String value;

      @CanIgnoreReturnValue
      public @NonNull Builder setValue(@NonNull String setterArg) {
        this.value = setterArg;
        return this;
      }

      public @NonNull PlacePageStringMetadataEntry build() {
        PlacePageStringMetadataEntry pigeonReturn = new PlacePageStringMetadataEntry();
        pigeonReturn.setKey(key);
        pigeonReturn.setValue(value);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(key);
      toListResult.add(value);
      return toListResult;
    }

    static @NonNull PlacePageStringMetadataEntry fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PlacePageStringMetadataEntry pigeonResult = new PlacePageStringMetadataEntry();
      Object key = pigeonVar_list.get(0);
      pigeonResult.setKey((String) key);
      Object value = pigeonVar_list.get(1);
      pigeonResult.setValue((String) value);
      return pigeonResult;
    }
  }

  /**
   * Structured place page payload.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PlacePageData {
    private @NonNull PlacePageFeatureId featureId;

    public @NonNull PlacePageFeatureId getFeatureId() {
      return featureId;
    }

    public void setFeatureId(@NonNull PlacePageFeatureId setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"featureId\" is null.");
      }
      this.featureId = setterArg;
    }

    private @NonNull Long objectType;

    public @NonNull Long getObjectType() {
      return objectType;
    }

    public void setObjectType(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"objectType\" is null.");
      }
      this.objectType = setterArg;
    }

    private @NonNull Long openingMode;

    public @NonNull Long getOpeningMode() {
      return openingMode;
    }

    public void setOpeningMode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"openingMode\" is null.");
      }
      this.openingMode = setterArg;
    }

    private @NonNull String title;

    public @NonNull String getTitle() {
      return title;
    }

    public void setTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"title\" is null.");
      }
      this.title = setterArg;
    }

    private @NonNull String secondaryTitle;

    public @NonNull String getSecondaryTitle() {
      return secondaryTitle;
    }

    public void setSecondaryTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"secondaryTitle\" is null.");
      }
      this.secondaryTitle = setterArg;
    }

    private @NonNull String subtitle;

    public @NonNull String getSubtitle() {
      return subtitle;
    }

    public void setSubtitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"subtitle\" is null.");
      }
      this.subtitle = setterArg;
    }

    private @NonNull String address;

    public @NonNull String getAddress() {
      return address;
    }

    public void setAddress(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"address\" is null.");
      }
      this.address = setterArg;
    }

    private @NonNull Double lat;

    public @NonNull Double getLat() {
      return lat;
    }

    public void setLat(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"lat\" is null.");
      }
      this.lat = setterArg;
    }

    private @NonNull Double lon;

    public @NonNull Double getLon() {
      return lon;
    }

    public void setLon(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"lon\" is null.");
      }
      this.lon = setterArg;
    }

    private @NonNull String wikiDescriptionHtml;

    public @NonNull String getWikiDescriptionHtml() {
      return wikiDescriptionHtml;
    }

    public void setWikiDescriptionHtml(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"wikiDescriptionHtml\" is null.");
      }
      this.wikiDescriptionHtml = setterArg;
    }

    private @NonNull Long roadType;

    public @NonNull Long getRoadType() {
      return roadType;
    }

    public void setRoadType(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"roadType\" is null.");
      }
      this.roadType = setterArg;
    }

    private @NonNull Boolean isRoutePoint;

    public @NonNull Boolean getIsRoutePoint() {
      return isRoutePoint;
    }

    public void setIsRoutePoint(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isRoutePoint\" is null.");
      }
      this.isRoutePoint = setterArg;
    }

    private @NonNull PlacePageCoordinates coordinates;

    public @NonNull PlacePageCoordinates getCoordinates() {
      return coordinates;
    }

    public void setCoordinates(@NonNull PlacePageCoordinates setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"coordinates\" is null.");
      }
      this.coordinates = setterArg;
    }

    private @NonNull List<String> rawTypes;

    public @NonNull List<String> getRawTypes() {
      return rawTypes;
    }

    public void setRawTypes(@NonNull List<String> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"rawTypes\" is null.");
      }
      this.rawTypes = setterArg;
    }

    private @NonNull List<PlacePageIntMetadataEntry> metadata;

    public @NonNull List<PlacePageIntMetadataEntry> getMetadata() {
      return metadata;
    }

    public void setMetadata(@NonNull List<PlacePageIntMetadataEntry> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"metadata\" is null.");
      }
      this.metadata = setterArg;
    }

    private @NonNull List<PlacePageStringMetadataEntry> metadataTags;

    public @NonNull List<PlacePageStringMetadataEntry> getMetadataTags() {
      return metadataTags;
    }

    public void setMetadataTags(@NonNull List<PlacePageStringMetadataEntry> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"metadataTags\" is null.");
      }
      this.metadataTags = setterArg;
    }

    private @Nullable Long bookmarkId;

    public @Nullable Long getBookmarkId() {
      return bookmarkId;
    }

    public void setBookmarkId(@Nullable Long setterArg) {
      this.bookmarkId = setterArg;
    }

    private @Nullable Long bookmarkCategoryId;

    public @Nullable Long getBookmarkCategoryId() {
      return bookmarkCategoryId;
    }

    public void setBookmarkCategoryId(@Nullable Long setterArg) {
      this.bookmarkCategoryId = setterArg;
    }

    private @Nullable Long trackId;

    public @Nullable Long getTrackId() {
      return trackId;
    }

    public void setTrackId(@Nullable Long setterArg) {
      this.trackId = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PlacePageData() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PlacePageData that = (PlacePageData) o;
      return pigeonDeepEquals(featureId, that.featureId) && pigeonDeepEquals(objectType, that.objectType) && pigeonDeepEquals(openingMode, that.openingMode) && pigeonDeepEquals(title, that.title) && pigeonDeepEquals(secondaryTitle, that.secondaryTitle) && pigeonDeepEquals(subtitle, that.subtitle) && pigeonDeepEquals(address, that.address) && pigeonDeepEquals(lat, that.lat) && pigeonDeepEquals(lon, that.lon) && pigeonDeepEquals(wikiDescriptionHtml, that.wikiDescriptionHtml) && pigeonDeepEquals(roadType, that.roadType) && pigeonDeepEquals(isRoutePoint, that.isRoutePoint) && pigeonDeepEquals(coordinates, that.coordinates) && pigeonDeepEquals(rawTypes, that.rawTypes) && pigeonDeepEquals(metadata, that.metadata) && pigeonDeepEquals(metadataTags, that.metadataTags) && pigeonDeepEquals(bookmarkId, that.bookmarkId) && pigeonDeepEquals(bookmarkCategoryId, that.bookmarkCategoryId) && pigeonDeepEquals(trackId, that.trackId);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), featureId, objectType, openingMode, title, secondaryTitle, subtitle, address, lat, lon, wikiDescriptionHtml, roadType, isRoutePoint, coordinates, rawTypes, metadata, metadataTags, bookmarkId, bookmarkCategoryId, trackId};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable PlacePageFeatureId featureId;

      @CanIgnoreReturnValue
      public @NonNull Builder setFeatureId(@NonNull PlacePageFeatureId setterArg) {
        this.featureId = setterArg;
        return this;
      }

      private @Nullable Long objectType;

      @CanIgnoreReturnValue
      public @NonNull Builder setObjectType(@NonNull Long setterArg) {
        this.objectType = setterArg;
        return this;
      }

      private @Nullable Long openingMode;

      @CanIgnoreReturnValue
      public @NonNull Builder setOpeningMode(@NonNull Long setterArg) {
        this.openingMode = setterArg;
        return this;
      }

      private @Nullable String title;

      @CanIgnoreReturnValue
      public @NonNull Builder setTitle(@NonNull String setterArg) {
        this.title = setterArg;
        return this;
      }

      private @Nullable String secondaryTitle;

      @CanIgnoreReturnValue
      public @NonNull Builder setSecondaryTitle(@NonNull String setterArg) {
        this.secondaryTitle = setterArg;
        return this;
      }

      private @Nullable String subtitle;

      @CanIgnoreReturnValue
      public @NonNull Builder setSubtitle(@NonNull String setterArg) {
        this.subtitle = setterArg;
        return this;
      }

      private @Nullable String address;

      @CanIgnoreReturnValue
      public @NonNull Builder setAddress(@NonNull String setterArg) {
        this.address = setterArg;
        return this;
      }

      private @Nullable Double lat;

      @CanIgnoreReturnValue
      public @NonNull Builder setLat(@NonNull Double setterArg) {
        this.lat = setterArg;
        return this;
      }

      private @Nullable Double lon;

      @CanIgnoreReturnValue
      public @NonNull Builder setLon(@NonNull Double setterArg) {
        this.lon = setterArg;
        return this;
      }

      private @Nullable String wikiDescriptionHtml;

      @CanIgnoreReturnValue
      public @NonNull Builder setWikiDescriptionHtml(@NonNull String setterArg) {
        this.wikiDescriptionHtml = setterArg;
        return this;
      }

      private @Nullable Long roadType;

      @CanIgnoreReturnValue
      public @NonNull Builder setRoadType(@NonNull Long setterArg) {
        this.roadType = setterArg;
        return this;
      }

      private @Nullable Boolean isRoutePoint;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsRoutePoint(@NonNull Boolean setterArg) {
        this.isRoutePoint = setterArg;
        return this;
      }

      private @Nullable PlacePageCoordinates coordinates;

      @CanIgnoreReturnValue
      public @NonNull Builder setCoordinates(@NonNull PlacePageCoordinates setterArg) {
        this.coordinates = setterArg;
        return this;
      }

      private @Nullable List<String> rawTypes;

      @CanIgnoreReturnValue
      public @NonNull Builder setRawTypes(@NonNull List<String> setterArg) {
        this.rawTypes = setterArg;
        return this;
      }

      private @Nullable List<PlacePageIntMetadataEntry> metadata;

      @CanIgnoreReturnValue
      public @NonNull Builder setMetadata(@NonNull List<PlacePageIntMetadataEntry> setterArg) {
        this.metadata = setterArg;
        return this;
      }

      private @Nullable List<PlacePageStringMetadataEntry> metadataTags;

      @CanIgnoreReturnValue
      public @NonNull Builder setMetadataTags(@NonNull List<PlacePageStringMetadataEntry> setterArg) {
        this.metadataTags = setterArg;
        return this;
      }

      private @Nullable Long bookmarkId;

      @CanIgnoreReturnValue
      public @NonNull Builder setBookmarkId(@Nullable Long setterArg) {
        this.bookmarkId = setterArg;
        return this;
      }

      private @Nullable Long bookmarkCategoryId;

      @CanIgnoreReturnValue
      public @NonNull Builder setBookmarkCategoryId(@Nullable Long setterArg) {
        this.bookmarkCategoryId = setterArg;
        return this;
      }

      private @Nullable Long trackId;

      @CanIgnoreReturnValue
      public @NonNull Builder setTrackId(@Nullable Long setterArg) {
        this.trackId = setterArg;
        return this;
      }

      public @NonNull PlacePageData build() {
        PlacePageData pigeonReturn = new PlacePageData();
        pigeonReturn.setFeatureId(featureId);
        pigeonReturn.setObjectType(objectType);
        pigeonReturn.setOpeningMode(openingMode);
        pigeonReturn.setTitle(title);
        pigeonReturn.setSecondaryTitle(secondaryTitle);
        pigeonReturn.setSubtitle(subtitle);
        pigeonReturn.setAddress(address);
        pigeonReturn.setLat(lat);
        pigeonReturn.setLon(lon);
        pigeonReturn.setWikiDescriptionHtml(wikiDescriptionHtml);
        pigeonReturn.setRoadType(roadType);
        pigeonReturn.setIsRoutePoint(isRoutePoint);
        pigeonReturn.setCoordinates(coordinates);
        pigeonReturn.setRawTypes(rawTypes);
        pigeonReturn.setMetadata(metadata);
        pigeonReturn.setMetadataTags(metadataTags);
        pigeonReturn.setBookmarkId(bookmarkId);
        pigeonReturn.setBookmarkCategoryId(bookmarkCategoryId);
        pigeonReturn.setTrackId(trackId);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(19);
      toListResult.add(featureId);
      toListResult.add(objectType);
      toListResult.add(openingMode);
      toListResult.add(title);
      toListResult.add(secondaryTitle);
      toListResult.add(subtitle);
      toListResult.add(address);
      toListResult.add(lat);
      toListResult.add(lon);
      toListResult.add(wikiDescriptionHtml);
      toListResult.add(roadType);
      toListResult.add(isRoutePoint);
      toListResult.add(coordinates);
      toListResult.add(rawTypes);
      toListResult.add(metadata);
      toListResult.add(metadataTags);
      toListResult.add(bookmarkId);
      toListResult.add(bookmarkCategoryId);
      toListResult.add(trackId);
      return toListResult;
    }

    static @NonNull PlacePageData fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PlacePageData pigeonResult = new PlacePageData();
      Object featureId = pigeonVar_list.get(0);
      pigeonResult.setFeatureId((PlacePageFeatureId) featureId);
      Object objectType = pigeonVar_list.get(1);
      pigeonResult.setObjectType((Long) objectType);
      Object openingMode = pigeonVar_list.get(2);
      pigeonResult.setOpeningMode((Long) openingMode);
      Object title = pigeonVar_list.get(3);
      pigeonResult.setTitle((String) title);
      Object secondaryTitle = pigeonVar_list.get(4);
      pigeonResult.setSecondaryTitle((String) secondaryTitle);
      Object subtitle = pigeonVar_list.get(5);
      pigeonResult.setSubtitle((String) subtitle);
      Object address = pigeonVar_list.get(6);
      pigeonResult.setAddress((String) address);
      Object lat = pigeonVar_list.get(7);
      pigeonResult.setLat((Double) lat);
      Object lon = pigeonVar_list.get(8);
      pigeonResult.setLon((Double) lon);
      Object wikiDescriptionHtml = pigeonVar_list.get(9);
      pigeonResult.setWikiDescriptionHtml((String) wikiDescriptionHtml);
      Object roadType = pigeonVar_list.get(10);
      pigeonResult.setRoadType((Long) roadType);
      Object isRoutePoint = pigeonVar_list.get(11);
      pigeonResult.setIsRoutePoint((Boolean) isRoutePoint);
      Object coordinates = pigeonVar_list.get(12);
      pigeonResult.setCoordinates((PlacePageCoordinates) coordinates);
      Object rawTypes = pigeonVar_list.get(13);
      pigeonResult.setRawTypes((List<String>) rawTypes);
      Object metadata = pigeonVar_list.get(14);
      pigeonResult.setMetadata((List<PlacePageIntMetadataEntry>) metadata);
      Object metadataTags = pigeonVar_list.get(15);
      pigeonResult.setMetadataTags((List<PlacePageStringMetadataEntry>) metadataTags);
      Object bookmarkId = pigeonVar_list.get(16);
      pigeonResult.setBookmarkId((Long) bookmarkId);
      Object bookmarkCategoryId = pigeonVar_list.get(17);
      pigeonResult.setBookmarkCategoryId((Long) bookmarkCategoryId);
      Object trackId = pigeonVar_list.get(18);
      pigeonResult.setTrackId((Long) trackId);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : RenderState.values()[((Long) value).intValue()];
        }
        case (byte) 130:
          return CreateMapSurfaceRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return ResizeMapSurfaceRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return MapPointerUpdateRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return MapPointerCoordinate.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return DrapeInteractionLineStyle.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 135:
          return DrapeInteractionGeometryRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 136:
          return PlacePageFeatureId.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 137:
          return PlacePageCoordinates.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 138:
          return PlacePageIntMetadataEntry.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 139:
          return PlacePageStringMetadataEntry.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 140:
          return PlacePageData.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof RenderState) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((RenderState) value).index);
      } else if (value instanceof CreateMapSurfaceRequest) {
        stream.write(130);
        writeValue(stream, ((CreateMapSurfaceRequest) value).toList());
      } else if (value instanceof ResizeMapSurfaceRequest) {
        stream.write(131);
        writeValue(stream, ((ResizeMapSurfaceRequest) value).toList());
      } else if (value instanceof MapPointerUpdateRequest) {
        stream.write(132);
        writeValue(stream, ((MapPointerUpdateRequest) value).toList());
      } else if (value instanceof MapPointerCoordinate) {
        stream.write(133);
        writeValue(stream, ((MapPointerCoordinate) value).toList());
      } else if (value instanceof DrapeInteractionLineStyle) {
        stream.write(134);
        writeValue(stream, ((DrapeInteractionLineStyle) value).toList());
      } else if (value instanceof DrapeInteractionGeometryRequest) {
        stream.write(135);
        writeValue(stream, ((DrapeInteractionGeometryRequest) value).toList());
      } else if (value instanceof PlacePageFeatureId) {
        stream.write(136);
        writeValue(stream, ((PlacePageFeatureId) value).toList());
      } else if (value instanceof PlacePageCoordinates) {
        stream.write(137);
        writeValue(stream, ((PlacePageCoordinates) value).toList());
      } else if (value instanceof PlacePageIntMetadataEntry) {
        stream.write(138);
        writeValue(stream, ((PlacePageIntMetadataEntry) value).toList());
      } else if (value instanceof PlacePageStringMetadataEntry) {
        stream.write(139);
        writeValue(stream, ((PlacePageStringMetadataEntry) value).toList());
      } else if (value instanceof PlacePageData) {
        stream.write(140);
        writeValue(stream, ((PlacePageData) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /**
   * Host API implemented by native platforms.
   *
   * Generated interface from Pigeon that represents a handler of messages from Flutter.
   */
  public interface AgusMapsHostApi {

    void extractMap(@NonNull String assetPath, @NonNull Result<String> result);

    void extractDataFiles(@NonNull Result<String> result);

    void getApkPath(@NonNull Result<String> result);

    void createMapSurface(@NonNull CreateMapSurfaceRequest request, @NonNull Result<Long> result);

    void resizeMapSurface(@NonNull ResizeMapSurfaceRequest request, @NonNull Result<Boolean> result);

    void destroyMapSurface(@NonNull Result<Boolean> result);
    /**
     * Updates the native global pointer tracker and returns the projected map
     * coordinate when the pointer is inside a ready map surface.
     */
    void updateMapPointer(@NonNull MapPointerUpdateRequest request, @NonNull NullableResult<MapPointerCoordinate> result);
    /** Updates native draw/edit interaction geometry with caller-provided styling. */
    void updateDrapeInteractionGeometry(@NonNull DrapeInteractionGeometryRequest request, @NonNull Result<Boolean> result);
    /** Returns the current place page payload if available. */
    void getCurrentPlacePage(@NonNull NullableResult<PlacePageData> result);
    /** Clears the active place page selection. */
    void clearPlacePageSelection(@NonNull Result<Boolean> result);

    /** The codec used by AgusMapsHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `AgusMapsHostApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable AgusMapsHostApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable AgusMapsHostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractMap" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String assetPathArg = (String) args.get(0);
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.extractMap(assetPathArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractDataFiles" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.extractDataFiles(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getApkPath" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getApkPath(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.createMapSurface" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                CreateMapSurfaceRequest requestArg = (CreateMapSurfaceRequest) args.get(0);
                Result<Long> resultCallback =
                    new Result<Long>() {
                      public void success(Long result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.createMapSurface(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.resizeMapSurface" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ResizeMapSurfaceRequest requestArg = (ResizeMapSurfaceRequest) args.get(0);
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.resizeMapSurface(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.destroyMapSurface" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.destroyMapSurface(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.updateMapPointer" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                MapPointerUpdateRequest requestArg = (MapPointerUpdateRequest) args.get(0);
                NullableResult<MapPointerCoordinate> resultCallback =
                    new NullableResult<MapPointerCoordinate>() {
                      public void success(MapPointerCoordinate result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.updateMapPointer(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.updateDrapeInteractionGeometry" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                DrapeInteractionGeometryRequest requestArg = (DrapeInteractionGeometryRequest) args.get(0);
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.updateDrapeInteractionGeometry(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getCurrentPlacePage" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                NullableResult<PlacePageData> resultCallback =
                    new NullableResult<PlacePageData>() {
                      public void success(PlacePageData result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getCurrentPlacePage(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.clearPlacePageSelection" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.clearPlacePageSelection(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /**
   * Flutter API implemented by Dart for low-frequency notifications.
   *
   * Generated class from Pigeon that represents Flutter messages that can be called from Java.
   */
  public static class AgusMapsFlutterApi {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public AgusMapsFlutterApi(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }
    public AgusMapsFlutterApi(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffix) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
    }

    /**
     * Public interface for sending reply.
     * The codec used by AgusMapsFlutterApi.
     */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    public void onMapReady(@NonNull Long surfaceIdArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onMapReady" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(surfaceIdArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void onRenderStateChanged(@NonNull RenderState stateArg, @Nullable Long surfaceIdArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onRenderStateChanged" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Arrays.asList(stateArg, surfaceIdArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void onPlacePageChanged(@Nullable PlacePageData placePageArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onPlacePageChanged" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(placePageArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
  }
}
