// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Rendering activity state for low-frequency notifications.
enum RenderState {
  /// Rendering is active (frames expected).
  active,
  /// Rendering is idle (no frames expected).
  idle,
}

/// Request payload for creating a map surface.
class CreateMapSurfaceRequest {
  CreateMapSurfaceRequest({
    this.width,
    this.height,
    this.density,
  });

  int? width;

  int? height;

  double? density;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      density,
    ];
  }

  Object encode() {
    return _toList();  }

  static CreateMapSurfaceRequest decode(Object result) {
    result as List<Object?>;
    return CreateMapSurfaceRequest(
      width: result[0] as int?,
      height: result[1] as int?,
      density: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateMapSurfaceRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request payload for resizing a map surface.
class ResizeMapSurfaceRequest {
  ResizeMapSurfaceRequest({
    required this.width,
    required this.height,
    this.density,
  });

  int width;

  int height;

  double? density;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      density,
    ];
  }

  Object encode() {
    return _toList();  }

  static ResizeMapSurfaceRequest decode(Object result) {
    result as List<Object?>;
    return ResizeMapSurfaceRequest(
      width: result[0]! as int,
      height: result[1]! as int,
      density: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ResizeMapSurfaceRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Stable identifier for a place page feature.
class PlacePageFeatureId {
  PlacePageFeatureId({
    required this.mwmName,
    required this.mwmVersion,
    required this.index,
  });

  String mwmName;

  int mwmVersion;

  int index;

  List<Object?> _toList() {
    return <Object?>[
      mwmName,
      mwmVersion,
      index,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlacePageFeatureId decode(Object result) {
    result as List<Object?>;
    return PlacePageFeatureId(
      mwmName: result[0]! as String,
      mwmVersion: result[1]! as int,
      index: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageFeatureId || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Formatted coordinates variants for a place page.
class PlacePageCoordinates {
  PlacePageCoordinates({
    this.decimal,
    this.dms,
    this.osm,
    this.olc,
    this.utm,
    this.mgrs,
  });

  String? decimal;

  String? dms;

  String? osm;

  String? olc;

  String? utm;

  String? mgrs;

  List<Object?> _toList() {
    return <Object?>[
      decimal,
      dms,
      osm,
      olc,
      utm,
      mgrs,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlacePageCoordinates decode(Object result) {
    result as List<Object?>;
    return PlacePageCoordinates(
      decimal: result[0] as String?,
      dms: result[1] as String?,
      osm: result[2] as String?,
      olc: result[3] as String?,
      utm: result[4] as String?,
      mgrs: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageCoordinates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Integer-keyed metadata entry.
class PlacePageIntMetadataEntry {
  PlacePageIntMetadataEntry({
    required this.key,
    required this.value,
  });

  int key;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      key,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlacePageIntMetadataEntry decode(Object result) {
    result as List<Object?>;
    return PlacePageIntMetadataEntry(
      key: result[0]! as int,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageIntMetadataEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// String-keyed metadata entry.
class PlacePageStringMetadataEntry {
  PlacePageStringMetadataEntry({
    required this.key,
    required this.value,
  });

  String key;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      key,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlacePageStringMetadataEntry decode(Object result) {
    result as List<Object?>;
    return PlacePageStringMetadataEntry(
      key: result[0]! as String,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageStringMetadataEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Structured place page payload.
class PlacePageData {
  PlacePageData({
    required this.featureId,
    required this.objectType,
    required this.openingMode,
    required this.title,
    required this.secondaryTitle,
    required this.subtitle,
    required this.address,
    required this.lat,
    required this.lon,
    required this.wikiDescriptionHtml,
    required this.roadType,
    required this.isRoutePoint,
    required this.coordinates,
    required this.rawTypes,
    required this.metadata,
    required this.metadataTags,
    this.bookmarkId,
    this.bookmarkCategoryId,
    this.trackId,
  });

  PlacePageFeatureId featureId;

  int objectType;

  int openingMode;

  String title;

  String secondaryTitle;

  String subtitle;

  String address;

  double lat;

  double lon;

  String wikiDescriptionHtml;

  int roadType;

  bool isRoutePoint;

  PlacePageCoordinates coordinates;

  List<String> rawTypes;

  List<PlacePageIntMetadataEntry> metadata;

  List<PlacePageStringMetadataEntry> metadataTags;

  int? bookmarkId;

  int? bookmarkCategoryId;

  int? trackId;

  List<Object?> _toList() {
    return <Object?>[
      featureId,
      objectType,
      openingMode,
      title,
      secondaryTitle,
      subtitle,
      address,
      lat,
      lon,
      wikiDescriptionHtml,
      roadType,
      isRoutePoint,
      coordinates,
      rawTypes,
      metadata,
      metadataTags,
      bookmarkId,
      bookmarkCategoryId,
      trackId,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlacePageData decode(Object result) {
    result as List<Object?>;
    return PlacePageData(
      featureId: result[0]! as PlacePageFeatureId,
      objectType: result[1]! as int,
      openingMode: result[2]! as int,
      title: result[3]! as String,
      secondaryTitle: result[4]! as String,
      subtitle: result[5]! as String,
      address: result[6]! as String,
      lat: result[7]! as double,
      lon: result[8]! as double,
      wikiDescriptionHtml: result[9]! as String,
      roadType: result[10]! as int,
      isRoutePoint: result[11]! as bool,
      coordinates: result[12]! as PlacePageCoordinates,
      rawTypes: (result[13] as List<Object?>?)!.cast<String>(),
      metadata: (result[14] as List<Object?>?)!.cast<PlacePageIntMetadataEntry>(),
      metadataTags: (result[15] as List<Object?>?)!.cast<PlacePageStringMetadataEntry>(),
      bookmarkId: result[16] as int?,
      bookmarkCategoryId: result[17] as int?,
      trackId: result[18] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RenderState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CreateMapSurfaceRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ResizeMapSurfaceRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PlacePageFeatureId) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PlacePageCoordinates) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PlacePageIntMetadataEntry) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PlacePageStringMetadataEntry) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PlacePageData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RenderState.values[value];
      case 130: 
        return CreateMapSurfaceRequest.decode(readValue(buffer)!);
      case 131: 
        return ResizeMapSurfaceRequest.decode(readValue(buffer)!);
      case 132: 
        return PlacePageFeatureId.decode(readValue(buffer)!);
      case 133: 
        return PlacePageCoordinates.decode(readValue(buffer)!);
      case 134: 
        return PlacePageIntMetadataEntry.decode(readValue(buffer)!);
      case 135: 
        return PlacePageStringMetadataEntry.decode(readValue(buffer)!);
      case 136: 
        return PlacePageData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API implemented by native platforms.
class AgusMapsHostApi {
  /// Constructor for [AgusMapsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AgusMapsHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> extractMap(String assetPath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractMap$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[assetPath]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> extractDataFiles() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractDataFiles$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> getApkPath() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getApkPath$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<int> createMapSurface(CreateMapSurfaceRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.createMapSurface$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<bool> resizeMapSurface(ResizeMapSurfaceRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.resizeMapSurface$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> destroyMapSurface() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.destroyMapSurface$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Returns the current place page payload if available.
  Future<PlacePageData?> getCurrentPlacePage() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getCurrentPlacePage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PlacePageData?);
    }
  }

  /// Clears the active place page selection.
  Future<bool> clearPlacePageSelection() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.clearPlacePageSelection$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

/// Flutter API implemented by Dart for low-frequency notifications.
abstract class AgusMapsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onMapReady(int surfaceId);

  void onRenderStateChanged(RenderState state, int? surfaceId);

  void onPlacePageChanged(PlacePageData? placePage);

  static void setUp(AgusMapsFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onMapReady$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onMapReady was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_surfaceId = (args[0] as int?);
          assert(arg_surfaceId != null,
              'Argument for dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onMapReady was null, expected non-null int.');
          try {
            api.onMapReady(arg_surfaceId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onRenderStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onRenderStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RenderState? arg_state = (args[0] as RenderState?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onRenderStateChanged was null, expected non-null RenderState.');
          final int? arg_surfaceId = (args[1] as int?);
          try {
            api.onRenderStateChanged(arg_state!, arg_surfaceId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onPlacePageChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onPlacePageChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PlacePageData? arg_placePage = (args[0] as PlacePageData?);
          try {
            api.onPlacePageChanged(arg_placePage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
