// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Rendering activity state for low-frequency notifications.
enum RenderState {
  /// Rendering is active (frames expected).
  active,

  /// Rendering is idle (no frames expected).
  idle,
}

/// Request payload for creating a map surface.
class CreateMapSurfaceRequest {
  CreateMapSurfaceRequest({
    this.width,
    this.height,
    this.density,
  });

  int? width;

  int? height;

  double? density;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      density,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CreateMapSurfaceRequest decode(Object result) {
    result as List<Object?>;
    return CreateMapSurfaceRequest(
      width: result[0] as int?,
      height: result[1] as int?,
      density: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateMapSurfaceRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(density, other.density);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Request payload for resizing a map surface.
class ResizeMapSurfaceRequest {
  ResizeMapSurfaceRequest({
    required this.width,
    required this.height,
    this.density,
  });

  int width;

  int height;

  double? density;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      density,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ResizeMapSurfaceRequest decode(Object result) {
    result as List<Object?>;
    return ResizeMapSurfaceRequest(
      width: result[0]! as int,
      height: result[1]! as int,
      density: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ResizeMapSurfaceRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(density, other.density);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Pointer position in the native map surface's physical pixel space.
class MapPointerUpdateRequest {
  MapPointerUpdateRequest({
    required this.physicalX,
    required this.physicalY,
    required this.insideMap,
  });

  double physicalX;

  double physicalY;

  bool insideMap;

  List<Object?> _toList() {
    return <Object?>[
      physicalX,
      physicalY,
      insideMap,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MapPointerUpdateRequest decode(Object result) {
    result as List<Object?>;
    return MapPointerUpdateRequest(
      physicalX: result[0]! as double,
      physicalY: result[1]! as double,
      insideMap: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MapPointerUpdateRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(physicalX, other.physicalX) &&
        _deepEquals(physicalY, other.physicalY) &&
        _deepEquals(insideMap, other.insideMap);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Native map-space pointer projection result.
class MapPointerCoordinate {
  MapPointerCoordinate({
    required this.physicalX,
    required this.physicalY,
    required this.insideMap,
    required this.lat,
    required this.lon,
  });

  double physicalX;

  double physicalY;

  bool insideMap;

  double lat;

  double lon;

  List<Object?> _toList() {
    return <Object?>[
      physicalX,
      physicalY,
      insideMap,
      lat,
      lon,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MapPointerCoordinate decode(Object result) {
    result as List<Object?>;
    return MapPointerCoordinate(
      physicalX: result[0]! as double,
      physicalY: result[1]! as double,
      insideMap: result[2]! as bool,
      lat: result[3]! as double,
      lon: result[4]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MapPointerCoordinate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(physicalX, other.physicalX) &&
        _deepEquals(physicalY, other.physicalY) &&
        _deepEquals(insideMap, other.insideMap) &&
        _deepEquals(lat, other.lat) &&
        _deepEquals(lon, other.lon);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Native interaction line style for transient draw/edit geometry.
class DrapeInteractionLineStyle {
  DrapeInteractionLineStyle({
    required this.colorRed,
    required this.colorGreen,
    required this.colorBlue,
    required this.opacity,
    required this.width,
    required this.dashed,
    required this.dashLength,
    required this.gapLength,
  });

  /// Red channel, 0-255.
  int colorRed;

  /// Green channel, 0-255.
  int colorGreen;

  /// Blue channel, 0-255.
  int colorBlue;

  /// Alpha opacity, 0.0-1.0.
  double opacity;

  /// Stroke width in physical pixels.
  double width;

  /// Whether the native renderer should split the line into dash segments.
  bool dashed;

  /// Dash length in physical pixels when [dashed] is true.
  double dashLength;

  /// Gap length in physical pixels when [dashed] is true.
  double gapLength;

  List<Object?> _toList() {
    return <Object?>[
      colorRed,
      colorGreen,
      colorBlue,
      opacity,
      width,
      dashed,
      dashLength,
      gapLength,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DrapeInteractionLineStyle decode(Object result) {
    result as List<Object?>;
    return DrapeInteractionLineStyle(
      colorRed: result[0]! as int,
      colorGreen: result[1]! as int,
      colorBlue: result[2]! as int,
      opacity: result[3]! as double,
      width: result[4]! as double,
      dashed: result[5]! as bool,
      dashLength: result[6]! as double,
      gapLength: result[7]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DrapeInteractionLineStyle ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(colorRed, other.colorRed) &&
        _deepEquals(colorGreen, other.colorGreen) &&
        _deepEquals(colorBlue, other.colorBlue) &&
        _deepEquals(opacity, other.opacity) &&
        _deepEquals(width, other.width) &&
        _deepEquals(dashed, other.dashed) &&
        _deepEquals(dashLength, other.dashLength) &&
        _deepEquals(gapLength, other.gapLength);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Native interaction geometry payload.
class DrapeInteractionGeometryRequest {
  DrapeInteractionGeometryRequest({
    required this.mode,
    this.geometryWkt,
    required this.lineStyle,
  });

  /// 0 inactive, 1 drawing, 2 editing feature.
  int mode;

  /// WKT geometry, or null to clear.
  String? geometryWkt;

  /// Style for line/edge geometry.
  DrapeInteractionLineStyle lineStyle;

  List<Object?> _toList() {
    return <Object?>[
      mode,
      geometryWkt,
      lineStyle,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DrapeInteractionGeometryRequest decode(Object result) {
    result as List<Object?>;
    return DrapeInteractionGeometryRequest(
      mode: result[0]! as int,
      geometryWkt: result[1] as String?,
      lineStyle: result[2]! as DrapeInteractionLineStyle,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DrapeInteractionGeometryRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mode, other.mode) &&
        _deepEquals(geometryWkt, other.geometryWkt) &&
        _deepEquals(lineStyle, other.lineStyle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Stable identifier for a place page feature.
class PlacePageFeatureId {
  PlacePageFeatureId({
    required this.mwmName,
    required this.mwmVersion,
    required this.index,
  });

  String mwmName;

  int mwmVersion;

  int index;

  List<Object?> _toList() {
    return <Object?>[
      mwmName,
      mwmVersion,
      index,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlacePageFeatureId decode(Object result) {
    result as List<Object?>;
    return PlacePageFeatureId(
      mwmName: result[0]! as String,
      mwmVersion: result[1]! as int,
      index: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageFeatureId || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mwmName, other.mwmName) &&
        _deepEquals(mwmVersion, other.mwmVersion) &&
        _deepEquals(index, other.index);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Formatted coordinates variants for a place page.
class PlacePageCoordinates {
  PlacePageCoordinates({
    this.decimal,
    this.dms,
    this.osm,
    this.olc,
    this.utm,
    this.mgrs,
  });

  String? decimal;

  String? dms;

  String? osm;

  String? olc;

  String? utm;

  String? mgrs;

  List<Object?> _toList() {
    return <Object?>[
      decimal,
      dms,
      osm,
      olc,
      utm,
      mgrs,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlacePageCoordinates decode(Object result) {
    result as List<Object?>;
    return PlacePageCoordinates(
      decimal: result[0] as String?,
      dms: result[1] as String?,
      osm: result[2] as String?,
      olc: result[3] as String?,
      utm: result[4] as String?,
      mgrs: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageCoordinates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(decimal, other.decimal) &&
        _deepEquals(dms, other.dms) &&
        _deepEquals(osm, other.osm) &&
        _deepEquals(olc, other.olc) &&
        _deepEquals(utm, other.utm) &&
        _deepEquals(mgrs, other.mgrs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Integer-keyed metadata entry.
class PlacePageIntMetadataEntry {
  PlacePageIntMetadataEntry({
    required this.key,
    required this.value,
  });

  int key;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      key,
      value,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlacePageIntMetadataEntry decode(Object result) {
    result as List<Object?>;
    return PlacePageIntMetadataEntry(
      key: result[0]! as int,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageIntMetadataEntry ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// String-keyed metadata entry.
class PlacePageStringMetadataEntry {
  PlacePageStringMetadataEntry({
    required this.key,
    required this.value,
  });

  String key;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      key,
      value,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlacePageStringMetadataEntry decode(Object result) {
    result as List<Object?>;
    return PlacePageStringMetadataEntry(
      key: result[0]! as String,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageStringMetadataEntry ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Structured place page payload.
class PlacePageData {
  PlacePageData({
    required this.featureId,
    required this.objectType,
    required this.openingMode,
    required this.title,
    required this.secondaryTitle,
    required this.subtitle,
    required this.address,
    required this.lat,
    required this.lon,
    required this.wikiDescriptionHtml,
    required this.roadType,
    required this.isRoutePoint,
    required this.coordinates,
    required this.rawTypes,
    required this.metadata,
    required this.metadataTags,
    this.bookmarkId,
    this.bookmarkCategoryId,
    this.trackId,
  });

  PlacePageFeatureId featureId;

  int objectType;

  int openingMode;

  String title;

  String secondaryTitle;

  String subtitle;

  String address;

  double lat;

  double lon;

  String wikiDescriptionHtml;

  int roadType;

  bool isRoutePoint;

  PlacePageCoordinates coordinates;

  List<String> rawTypes;

  List<PlacePageIntMetadataEntry> metadata;

  List<PlacePageStringMetadataEntry> metadataTags;

  int? bookmarkId;

  int? bookmarkCategoryId;

  int? trackId;

  List<Object?> _toList() {
    return <Object?>[
      featureId,
      objectType,
      openingMode,
      title,
      secondaryTitle,
      subtitle,
      address,
      lat,
      lon,
      wikiDescriptionHtml,
      roadType,
      isRoutePoint,
      coordinates,
      rawTypes,
      metadata,
      metadataTags,
      bookmarkId,
      bookmarkCategoryId,
      trackId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlacePageData decode(Object result) {
    result as List<Object?>;
    return PlacePageData(
      featureId: result[0]! as PlacePageFeatureId,
      objectType: result[1]! as int,
      openingMode: result[2]! as int,
      title: result[3]! as String,
      secondaryTitle: result[4]! as String,
      subtitle: result[5]! as String,
      address: result[6]! as String,
      lat: result[7]! as double,
      lon: result[8]! as double,
      wikiDescriptionHtml: result[9]! as String,
      roadType: result[10]! as int,
      isRoutePoint: result[11]! as bool,
      coordinates: result[12]! as PlacePageCoordinates,
      rawTypes: (result[13]! as List<Object?>).cast<String>(),
      metadata:
          (result[14]! as List<Object?>).cast<PlacePageIntMetadataEntry>(),
      metadataTags:
          (result[15]! as List<Object?>).cast<PlacePageStringMetadataEntry>(),
      bookmarkId: result[16] as int?,
      bookmarkCategoryId: result[17] as int?,
      trackId: result[18] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlacePageData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(featureId, other.featureId) &&
        _deepEquals(objectType, other.objectType) &&
        _deepEquals(openingMode, other.openingMode) &&
        _deepEquals(title, other.title) &&
        _deepEquals(secondaryTitle, other.secondaryTitle) &&
        _deepEquals(subtitle, other.subtitle) &&
        _deepEquals(address, other.address) &&
        _deepEquals(lat, other.lat) &&
        _deepEquals(lon, other.lon) &&
        _deepEquals(wikiDescriptionHtml, other.wikiDescriptionHtml) &&
        _deepEquals(roadType, other.roadType) &&
        _deepEquals(isRoutePoint, other.isRoutePoint) &&
        _deepEquals(coordinates, other.coordinates) &&
        _deepEquals(rawTypes, other.rawTypes) &&
        _deepEquals(metadata, other.metadata) &&
        _deepEquals(metadataTags, other.metadataTags) &&
        _deepEquals(bookmarkId, other.bookmarkId) &&
        _deepEquals(bookmarkCategoryId, other.bookmarkCategoryId) &&
        _deepEquals(trackId, other.trackId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RenderState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CreateMapSurfaceRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ResizeMapSurfaceRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is MapPointerUpdateRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is MapPointerCoordinate) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is DrapeInteractionLineStyle) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is DrapeInteractionGeometryRequest) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PlacePageFeatureId) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PlacePageCoordinates) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PlacePageIntMetadataEntry) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is PlacePageStringMetadataEntry) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is PlacePageData) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RenderState.values[value];
      case 130:
        return CreateMapSurfaceRequest.decode(readValue(buffer)!);
      case 131:
        return ResizeMapSurfaceRequest.decode(readValue(buffer)!);
      case 132:
        return MapPointerUpdateRequest.decode(readValue(buffer)!);
      case 133:
        return MapPointerCoordinate.decode(readValue(buffer)!);
      case 134:
        return DrapeInteractionLineStyle.decode(readValue(buffer)!);
      case 135:
        return DrapeInteractionGeometryRequest.decode(readValue(buffer)!);
      case 136:
        return PlacePageFeatureId.decode(readValue(buffer)!);
      case 137:
        return PlacePageCoordinates.decode(readValue(buffer)!);
      case 138:
        return PlacePageIntMetadataEntry.decode(readValue(buffer)!);
      case 139:
        return PlacePageStringMetadataEntry.decode(readValue(buffer)!);
      case 140:
        return PlacePageData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API implemented by native platforms.
class AgusMapsHostApi {
  /// Constructor for [AgusMapsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AgusMapsHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> extractMap(String assetPath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractMap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[assetPath]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> extractDataFiles() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.extractDataFiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> getApkPath() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getApkPath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<int> createMapSurface(CreateMapSurfaceRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.createMapSurface$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<bool> resizeMapSurface(ResizeMapSurfaceRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.resizeMapSurface$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> destroyMapSurface() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.destroyMapSurface$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Updates the native global pointer tracker and returns the projected map
  /// coordinate when the pointer is inside a ready map surface.
  Future<MapPointerCoordinate?> updateMapPointer(
      MapPointerUpdateRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.updateMapPointer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as MapPointerCoordinate?;
  }

  /// Updates native draw/edit interaction geometry with caller-provided styling.
  Future<bool> updateDrapeInteractionGeometry(
      DrapeInteractionGeometryRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.updateDrapeInteractionGeometry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Returns the current place page payload if available.
  Future<PlacePageData?> getCurrentPlacePage() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.getCurrentPlacePage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as PlacePageData?;
  }

  /// Clears the active place page selection.
  Future<bool> clearPlacePageSelection() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.agus_maps_flutter.AgusMapsHostApi.clearPlacePageSelection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Flutter API implemented by Dart for low-frequency notifications.
abstract class AgusMapsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onMapReady(int surfaceId);

  void onRenderStateChanged(RenderState state, int? surfaceId);

  void onPlacePageChanged(PlacePageData? placePage);

  static void setUp(
    AgusMapsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onMapReady$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_surfaceId = args[0]! as int;
          try {
            api.onMapReady(arg_surfaceId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onRenderStateChanged$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final RenderState arg_state = args[0]! as RenderState;
          final int? arg_surfaceId = args[1] as int?;
          try {
            api.onRenderStateChanged(arg_state, arg_surfaceId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.agus_maps_flutter.AgusMapsFlutterApi.onPlacePageChanged$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlacePageData? arg_placePage = args[0] as PlacePageData?;
          try {
            api.onPlacePageChanged(arg_placePage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
