// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_AGUS_MAPS_API_G_H_
#define PIGEON_AGUS_MAPS_API_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * agus_maps_flutterRenderState:
 * AGUS_MAPS_FLUTTER_RENDER_STATE_ACTIVE:
 * Rendering is active (frames expected).
 * AGUS_MAPS_FLUTTER_RENDER_STATE_IDLE:
 * Rendering is idle (no frames expected).
 *
 * Rendering activity state for low-frequency notifications.
 */
typedef enum {
  AGUS_MAPS_FLUTTER_RENDER_STATE_ACTIVE = 0,
  AGUS_MAPS_FLUTTER_RENDER_STATE_IDLE = 1
} agus_maps_flutterRenderState;

/**
 * agus_maps_flutterCreateMapSurfaceRequest:
 *
 * Request payload for creating a map surface.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterCreateMapSurfaceRequest, agus_maps_flutter_create_map_surface_request, AGUS_MAPS_FLUTTER, CREATE_MAP_SURFACE_REQUEST, GObject)

/**
 * agus_maps_flutter_create_map_surface_request_new:
 * width: field in this object.
 * height: field in this object.
 * density: field in this object.
 *
 * Creates a new #CreateMapSurfaceRequest object.
 *
 * Returns: a new #agus_maps_flutterCreateMapSurfaceRequest
 */
agus_maps_flutterCreateMapSurfaceRequest* agus_maps_flutter_create_map_surface_request_new(int64_t* width, int64_t* height, double* density);

/**
 * agus_maps_flutter_create_map_surface_request_get_width
 * @object: a #agus_maps_flutterCreateMapSurfaceRequest.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t* agus_maps_flutter_create_map_surface_request_get_width(agus_maps_flutterCreateMapSurfaceRequest* object);

/**
 * agus_maps_flutter_create_map_surface_request_get_height
 * @object: a #agus_maps_flutterCreateMapSurfaceRequest.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t* agus_maps_flutter_create_map_surface_request_get_height(agus_maps_flutterCreateMapSurfaceRequest* object);

/**
 * agus_maps_flutter_create_map_surface_request_get_density
 * @object: a #agus_maps_flutterCreateMapSurfaceRequest.
 *
 * Gets the value of the density field of @object.
 *
 * Returns: the field value.
 */
double* agus_maps_flutter_create_map_surface_request_get_density(agus_maps_flutterCreateMapSurfaceRequest* object);

/**
 * agus_maps_flutter_create_map_surface_request_equals:
 * @a: a #agus_maps_flutterCreateMapSurfaceRequest.
 * @b: another #agus_maps_flutterCreateMapSurfaceRequest.
 *
 * Checks if two #agus_maps_flutterCreateMapSurfaceRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_create_map_surface_request_equals(agus_maps_flutterCreateMapSurfaceRequest* a, agus_maps_flutterCreateMapSurfaceRequest* b);

/**
 * agus_maps_flutter_create_map_surface_request_hash:
 * @object: a #agus_maps_flutterCreateMapSurfaceRequest.
 *
 * Calculates a hash code for a #agus_maps_flutterCreateMapSurfaceRequest object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_create_map_surface_request_hash(agus_maps_flutterCreateMapSurfaceRequest* object);

/**
 * agus_maps_flutterResizeMapSurfaceRequest:
 *
 * Request payload for resizing a map surface.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterResizeMapSurfaceRequest, agus_maps_flutter_resize_map_surface_request, AGUS_MAPS_FLUTTER, RESIZE_MAP_SURFACE_REQUEST, GObject)

/**
 * agus_maps_flutter_resize_map_surface_request_new:
 * width: field in this object.
 * height: field in this object.
 * density: field in this object.
 *
 * Creates a new #ResizeMapSurfaceRequest object.
 *
 * Returns: a new #agus_maps_flutterResizeMapSurfaceRequest
 */
agus_maps_flutterResizeMapSurfaceRequest* agus_maps_flutter_resize_map_surface_request_new(int64_t width, int64_t height, double* density);

/**
 * agus_maps_flutter_resize_map_surface_request_get_width
 * @object: a #agus_maps_flutterResizeMapSurfaceRequest.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_resize_map_surface_request_get_width(agus_maps_flutterResizeMapSurfaceRequest* object);

/**
 * agus_maps_flutter_resize_map_surface_request_get_height
 * @object: a #agus_maps_flutterResizeMapSurfaceRequest.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_resize_map_surface_request_get_height(agus_maps_flutterResizeMapSurfaceRequest* object);

/**
 * agus_maps_flutter_resize_map_surface_request_get_density
 * @object: a #agus_maps_flutterResizeMapSurfaceRequest.
 *
 * Gets the value of the density field of @object.
 *
 * Returns: the field value.
 */
double* agus_maps_flutter_resize_map_surface_request_get_density(agus_maps_flutterResizeMapSurfaceRequest* object);

/**
 * agus_maps_flutter_resize_map_surface_request_equals:
 * @a: a #agus_maps_flutterResizeMapSurfaceRequest.
 * @b: another #agus_maps_flutterResizeMapSurfaceRequest.
 *
 * Checks if two #agus_maps_flutterResizeMapSurfaceRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_resize_map_surface_request_equals(agus_maps_flutterResizeMapSurfaceRequest* a, agus_maps_flutterResizeMapSurfaceRequest* b);

/**
 * agus_maps_flutter_resize_map_surface_request_hash:
 * @object: a #agus_maps_flutterResizeMapSurfaceRequest.
 *
 * Calculates a hash code for a #agus_maps_flutterResizeMapSurfaceRequest object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_resize_map_surface_request_hash(agus_maps_flutterResizeMapSurfaceRequest* object);

/**
 * agus_maps_flutterMapPointerUpdateRequest:
 *
 * Pointer position in the native map surface's physical pixel space.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterMapPointerUpdateRequest, agus_maps_flutter_map_pointer_update_request, AGUS_MAPS_FLUTTER, MAP_POINTER_UPDATE_REQUEST, GObject)

/**
 * agus_maps_flutter_map_pointer_update_request_new:
 * physical_x: field in this object.
 * physical_y: field in this object.
 * inside_map: field in this object.
 *
 * Creates a new #MapPointerUpdateRequest object.
 *
 * Returns: a new #agus_maps_flutterMapPointerUpdateRequest
 */
agus_maps_flutterMapPointerUpdateRequest* agus_maps_flutter_map_pointer_update_request_new(double physical_x, double physical_y, gboolean inside_map);

/**
 * agus_maps_flutter_map_pointer_update_request_get_physical_x
 * @object: a #agus_maps_flutterMapPointerUpdateRequest.
 *
 * Gets the value of the physicalX field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_map_pointer_update_request_get_physical_x(agus_maps_flutterMapPointerUpdateRequest* object);

/**
 * agus_maps_flutter_map_pointer_update_request_get_physical_y
 * @object: a #agus_maps_flutterMapPointerUpdateRequest.
 *
 * Gets the value of the physicalY field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_map_pointer_update_request_get_physical_y(agus_maps_flutterMapPointerUpdateRequest* object);

/**
 * agus_maps_flutter_map_pointer_update_request_get_inside_map
 * @object: a #agus_maps_flutterMapPointerUpdateRequest.
 *
 * Gets the value of the insideMap field of @object.
 *
 * Returns: the field value.
 */
gboolean agus_maps_flutter_map_pointer_update_request_get_inside_map(agus_maps_flutterMapPointerUpdateRequest* object);

/**
 * agus_maps_flutter_map_pointer_update_request_equals:
 * @a: a #agus_maps_flutterMapPointerUpdateRequest.
 * @b: another #agus_maps_flutterMapPointerUpdateRequest.
 *
 * Checks if two #agus_maps_flutterMapPointerUpdateRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_map_pointer_update_request_equals(agus_maps_flutterMapPointerUpdateRequest* a, agus_maps_flutterMapPointerUpdateRequest* b);

/**
 * agus_maps_flutter_map_pointer_update_request_hash:
 * @object: a #agus_maps_flutterMapPointerUpdateRequest.
 *
 * Calculates a hash code for a #agus_maps_flutterMapPointerUpdateRequest object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_map_pointer_update_request_hash(agus_maps_flutterMapPointerUpdateRequest* object);

/**
 * agus_maps_flutterMapPointerCoordinate:
 *
 * Native map-space pointer projection result.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterMapPointerCoordinate, agus_maps_flutter_map_pointer_coordinate, AGUS_MAPS_FLUTTER, MAP_POINTER_COORDINATE, GObject)

/**
 * agus_maps_flutter_map_pointer_coordinate_new:
 * physical_x: field in this object.
 * physical_y: field in this object.
 * inside_map: field in this object.
 * lat: field in this object.
 * lon: field in this object.
 *
 * Creates a new #MapPointerCoordinate object.
 *
 * Returns: a new #agus_maps_flutterMapPointerCoordinate
 */
agus_maps_flutterMapPointerCoordinate* agus_maps_flutter_map_pointer_coordinate_new(double physical_x, double physical_y, gboolean inside_map, double lat, double lon);

/**
 * agus_maps_flutter_map_pointer_coordinate_get_physical_x
 * @object: a #agus_maps_flutterMapPointerCoordinate.
 *
 * Gets the value of the physicalX field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_map_pointer_coordinate_get_physical_x(agus_maps_flutterMapPointerCoordinate* object);

/**
 * agus_maps_flutter_map_pointer_coordinate_get_physical_y
 * @object: a #agus_maps_flutterMapPointerCoordinate.
 *
 * Gets the value of the physicalY field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_map_pointer_coordinate_get_physical_y(agus_maps_flutterMapPointerCoordinate* object);

/**
 * agus_maps_flutter_map_pointer_coordinate_get_inside_map
 * @object: a #agus_maps_flutterMapPointerCoordinate.
 *
 * Gets the value of the insideMap field of @object.
 *
 * Returns: the field value.
 */
gboolean agus_maps_flutter_map_pointer_coordinate_get_inside_map(agus_maps_flutterMapPointerCoordinate* object);

/**
 * agus_maps_flutter_map_pointer_coordinate_get_lat
 * @object: a #agus_maps_flutterMapPointerCoordinate.
 *
 * Gets the value of the lat field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_map_pointer_coordinate_get_lat(agus_maps_flutterMapPointerCoordinate* object);

/**
 * agus_maps_flutter_map_pointer_coordinate_get_lon
 * @object: a #agus_maps_flutterMapPointerCoordinate.
 *
 * Gets the value of the lon field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_map_pointer_coordinate_get_lon(agus_maps_flutterMapPointerCoordinate* object);

/**
 * agus_maps_flutter_map_pointer_coordinate_equals:
 * @a: a #agus_maps_flutterMapPointerCoordinate.
 * @b: another #agus_maps_flutterMapPointerCoordinate.
 *
 * Checks if two #agus_maps_flutterMapPointerCoordinate objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_map_pointer_coordinate_equals(agus_maps_flutterMapPointerCoordinate* a, agus_maps_flutterMapPointerCoordinate* b);

/**
 * agus_maps_flutter_map_pointer_coordinate_hash:
 * @object: a #agus_maps_flutterMapPointerCoordinate.
 *
 * Calculates a hash code for a #agus_maps_flutterMapPointerCoordinate object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_map_pointer_coordinate_hash(agus_maps_flutterMapPointerCoordinate* object);

/**
 * agus_maps_flutterDrapeInteractionLineStyle:
 *
 * Native interaction line style for transient draw/edit geometry.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterDrapeInteractionLineStyle, agus_maps_flutter_drape_interaction_line_style, AGUS_MAPS_FLUTTER, DRAPE_INTERACTION_LINE_STYLE, GObject)

/**
 * agus_maps_flutter_drape_interaction_line_style_new:
 * color_red: field in this object.
 * color_green: field in this object.
 * color_blue: field in this object.
 * opacity: field in this object.
 * width: field in this object.
 * dashed: field in this object.
 * dash_length: field in this object.
 * gap_length: field in this object.
 *
 * Creates a new #DrapeInteractionLineStyle object.
 *
 * Returns: a new #agus_maps_flutterDrapeInteractionLineStyle
 */
agus_maps_flutterDrapeInteractionLineStyle* agus_maps_flutter_drape_interaction_line_style_new(int64_t color_red, int64_t color_green, int64_t color_blue, double opacity, double width, gboolean dashed, double dash_length, double gap_length);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_color_red
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Red channel, 0-255.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_drape_interaction_line_style_get_color_red(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_color_green
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Green channel, 0-255.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_drape_interaction_line_style_get_color_green(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_color_blue
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Blue channel, 0-255.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_drape_interaction_line_style_get_color_blue(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_opacity
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Alpha opacity, 0.0-1.0.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_drape_interaction_line_style_get_opacity(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_width
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Stroke width in physical pixels.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_drape_interaction_line_style_get_width(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_dashed
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Whether the native renderer should split the line into dash segments.
 *
 * Returns: the field value.
 */
gboolean agus_maps_flutter_drape_interaction_line_style_get_dashed(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_dash_length
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Dash length in physical pixels when [dashed] is true.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_drape_interaction_line_style_get_dash_length(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_get_gap_length
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Gap length in physical pixels when [dashed] is true.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_drape_interaction_line_style_get_gap_length(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutter_drape_interaction_line_style_equals:
 * @a: a #agus_maps_flutterDrapeInteractionLineStyle.
 * @b: another #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Checks if two #agus_maps_flutterDrapeInteractionLineStyle objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_drape_interaction_line_style_equals(agus_maps_flutterDrapeInteractionLineStyle* a, agus_maps_flutterDrapeInteractionLineStyle* b);

/**
 * agus_maps_flutter_drape_interaction_line_style_hash:
 * @object: a #agus_maps_flutterDrapeInteractionLineStyle.
 *
 * Calculates a hash code for a #agus_maps_flutterDrapeInteractionLineStyle object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_drape_interaction_line_style_hash(agus_maps_flutterDrapeInteractionLineStyle* object);

/**
 * agus_maps_flutterDrapeInteractionGeometryRequest:
 *
 * Native interaction geometry payload.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterDrapeInteractionGeometryRequest, agus_maps_flutter_drape_interaction_geometry_request, AGUS_MAPS_FLUTTER, DRAPE_INTERACTION_GEOMETRY_REQUEST, GObject)

/**
 * agus_maps_flutter_drape_interaction_geometry_request_new:
 * mode: field in this object.
 * geometry_wkt: field in this object.
 * line_style: field in this object.
 *
 * Creates a new #DrapeInteractionGeometryRequest object.
 *
 * Returns: a new #agus_maps_flutterDrapeInteractionGeometryRequest
 */
agus_maps_flutterDrapeInteractionGeometryRequest* agus_maps_flutter_drape_interaction_geometry_request_new(int64_t mode, const gchar* geometry_wkt, agus_maps_flutterDrapeInteractionLineStyle* line_style);

/**
 * agus_maps_flutter_drape_interaction_geometry_request_get_mode
 * @object: a #agus_maps_flutterDrapeInteractionGeometryRequest.
 *
 * 0 inactive, 1 drawing, 2 editing feature.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_drape_interaction_geometry_request_get_mode(agus_maps_flutterDrapeInteractionGeometryRequest* object);

/**
 * agus_maps_flutter_drape_interaction_geometry_request_get_geometry_wkt
 * @object: a #agus_maps_flutterDrapeInteractionGeometryRequest.
 *
 * WKT geometry, or null to clear.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_drape_interaction_geometry_request_get_geometry_wkt(agus_maps_flutterDrapeInteractionGeometryRequest* object);

/**
 * agus_maps_flutter_drape_interaction_geometry_request_get_line_style
 * @object: a #agus_maps_flutterDrapeInteractionGeometryRequest.
 *
 * Style for line/edge geometry.
 *
 * Returns: the field value.
 */
agus_maps_flutterDrapeInteractionLineStyle* agus_maps_flutter_drape_interaction_geometry_request_get_line_style(agus_maps_flutterDrapeInteractionGeometryRequest* object);

/**
 * agus_maps_flutter_drape_interaction_geometry_request_equals:
 * @a: a #agus_maps_flutterDrapeInteractionGeometryRequest.
 * @b: another #agus_maps_flutterDrapeInteractionGeometryRequest.
 *
 * Checks if two #agus_maps_flutterDrapeInteractionGeometryRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_drape_interaction_geometry_request_equals(agus_maps_flutterDrapeInteractionGeometryRequest* a, agus_maps_flutterDrapeInteractionGeometryRequest* b);

/**
 * agus_maps_flutter_drape_interaction_geometry_request_hash:
 * @object: a #agus_maps_flutterDrapeInteractionGeometryRequest.
 *
 * Calculates a hash code for a #agus_maps_flutterDrapeInteractionGeometryRequest object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_drape_interaction_geometry_request_hash(agus_maps_flutterDrapeInteractionGeometryRequest* object);

/**
 * agus_maps_flutterPlacePageFeatureId:
 *
 * Stable identifier for a place page feature.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterPlacePageFeatureId, agus_maps_flutter_place_page_feature_id, AGUS_MAPS_FLUTTER, PLACE_PAGE_FEATURE_ID, GObject)

/**
 * agus_maps_flutter_place_page_feature_id_new:
 * mwm_name: field in this object.
 * mwm_version: field in this object.
 * index: field in this object.
 *
 * Creates a new #PlacePageFeatureId object.
 *
 * Returns: a new #agus_maps_flutterPlacePageFeatureId
 */
agus_maps_flutterPlacePageFeatureId* agus_maps_flutter_place_page_feature_id_new(const gchar* mwm_name, int64_t mwm_version, int64_t index);

/**
 * agus_maps_flutter_place_page_feature_id_get_mwm_name
 * @object: a #agus_maps_flutterPlacePageFeatureId.
 *
 * Gets the value of the mwmName field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_feature_id_get_mwm_name(agus_maps_flutterPlacePageFeatureId* object);

/**
 * agus_maps_flutter_place_page_feature_id_get_mwm_version
 * @object: a #agus_maps_flutterPlacePageFeatureId.
 *
 * Gets the value of the mwmVersion field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_place_page_feature_id_get_mwm_version(agus_maps_flutterPlacePageFeatureId* object);

/**
 * agus_maps_flutter_place_page_feature_id_get_index
 * @object: a #agus_maps_flutterPlacePageFeatureId.
 *
 * Gets the value of the index field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_place_page_feature_id_get_index(agus_maps_flutterPlacePageFeatureId* object);

/**
 * agus_maps_flutter_place_page_feature_id_equals:
 * @a: a #agus_maps_flutterPlacePageFeatureId.
 * @b: another #agus_maps_flutterPlacePageFeatureId.
 *
 * Checks if two #agus_maps_flutterPlacePageFeatureId objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_place_page_feature_id_equals(agus_maps_flutterPlacePageFeatureId* a, agus_maps_flutterPlacePageFeatureId* b);

/**
 * agus_maps_flutter_place_page_feature_id_hash:
 * @object: a #agus_maps_flutterPlacePageFeatureId.
 *
 * Calculates a hash code for a #agus_maps_flutterPlacePageFeatureId object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_place_page_feature_id_hash(agus_maps_flutterPlacePageFeatureId* object);

/**
 * agus_maps_flutterPlacePageCoordinates:
 *
 * Formatted coordinates variants for a place page.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterPlacePageCoordinates, agus_maps_flutter_place_page_coordinates, AGUS_MAPS_FLUTTER, PLACE_PAGE_COORDINATES, GObject)

/**
 * agus_maps_flutter_place_page_coordinates_new:
 * decimal: field in this object.
 * dms: field in this object.
 * osm: field in this object.
 * olc: field in this object.
 * utm: field in this object.
 * mgrs: field in this object.
 *
 * Creates a new #PlacePageCoordinates object.
 *
 * Returns: a new #agus_maps_flutterPlacePageCoordinates
 */
agus_maps_flutterPlacePageCoordinates* agus_maps_flutter_place_page_coordinates_new(const gchar* decimal, const gchar* dms, const gchar* osm, const gchar* olc, const gchar* utm, const gchar* mgrs);

/**
 * agus_maps_flutter_place_page_coordinates_get_decimal
 * @object: a #agus_maps_flutterPlacePageCoordinates.
 *
 * Gets the value of the decimal field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_coordinates_get_decimal(agus_maps_flutterPlacePageCoordinates* object);

/**
 * agus_maps_flutter_place_page_coordinates_get_dms
 * @object: a #agus_maps_flutterPlacePageCoordinates.
 *
 * Gets the value of the dms field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_coordinates_get_dms(agus_maps_flutterPlacePageCoordinates* object);

/**
 * agus_maps_flutter_place_page_coordinates_get_osm
 * @object: a #agus_maps_flutterPlacePageCoordinates.
 *
 * Gets the value of the osm field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_coordinates_get_osm(agus_maps_flutterPlacePageCoordinates* object);

/**
 * agus_maps_flutter_place_page_coordinates_get_olc
 * @object: a #agus_maps_flutterPlacePageCoordinates.
 *
 * Gets the value of the olc field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_coordinates_get_olc(agus_maps_flutterPlacePageCoordinates* object);

/**
 * agus_maps_flutter_place_page_coordinates_get_utm
 * @object: a #agus_maps_flutterPlacePageCoordinates.
 *
 * Gets the value of the utm field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_coordinates_get_utm(agus_maps_flutterPlacePageCoordinates* object);

/**
 * agus_maps_flutter_place_page_coordinates_get_mgrs
 * @object: a #agus_maps_flutterPlacePageCoordinates.
 *
 * Gets the value of the mgrs field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_coordinates_get_mgrs(agus_maps_flutterPlacePageCoordinates* object);

/**
 * agus_maps_flutter_place_page_coordinates_equals:
 * @a: a #agus_maps_flutterPlacePageCoordinates.
 * @b: another #agus_maps_flutterPlacePageCoordinates.
 *
 * Checks if two #agus_maps_flutterPlacePageCoordinates objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_place_page_coordinates_equals(agus_maps_flutterPlacePageCoordinates* a, agus_maps_flutterPlacePageCoordinates* b);

/**
 * agus_maps_flutter_place_page_coordinates_hash:
 * @object: a #agus_maps_flutterPlacePageCoordinates.
 *
 * Calculates a hash code for a #agus_maps_flutterPlacePageCoordinates object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_place_page_coordinates_hash(agus_maps_flutterPlacePageCoordinates* object);

/**
 * agus_maps_flutterPlacePageIntMetadataEntry:
 *
 * Integer-keyed metadata entry.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterPlacePageIntMetadataEntry, agus_maps_flutter_place_page_int_metadata_entry, AGUS_MAPS_FLUTTER, PLACE_PAGE_INT_METADATA_ENTRY, GObject)

/**
 * agus_maps_flutter_place_page_int_metadata_entry_new:
 * key: field in this object.
 * value: field in this object.
 *
 * Creates a new #PlacePageIntMetadataEntry object.
 *
 * Returns: a new #agus_maps_flutterPlacePageIntMetadataEntry
 */
agus_maps_flutterPlacePageIntMetadataEntry* agus_maps_flutter_place_page_int_metadata_entry_new(int64_t key, const gchar* value);

/**
 * agus_maps_flutter_place_page_int_metadata_entry_get_key
 * @object: a #agus_maps_flutterPlacePageIntMetadataEntry.
 *
 * Gets the value of the key field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_place_page_int_metadata_entry_get_key(agus_maps_flutterPlacePageIntMetadataEntry* object);

/**
 * agus_maps_flutter_place_page_int_metadata_entry_get_value
 * @object: a #agus_maps_flutterPlacePageIntMetadataEntry.
 *
 * Gets the value of the value field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_int_metadata_entry_get_value(agus_maps_flutterPlacePageIntMetadataEntry* object);

/**
 * agus_maps_flutter_place_page_int_metadata_entry_equals:
 * @a: a #agus_maps_flutterPlacePageIntMetadataEntry.
 * @b: another #agus_maps_flutterPlacePageIntMetadataEntry.
 *
 * Checks if two #agus_maps_flutterPlacePageIntMetadataEntry objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_place_page_int_metadata_entry_equals(agus_maps_flutterPlacePageIntMetadataEntry* a, agus_maps_flutterPlacePageIntMetadataEntry* b);

/**
 * agus_maps_flutter_place_page_int_metadata_entry_hash:
 * @object: a #agus_maps_flutterPlacePageIntMetadataEntry.
 *
 * Calculates a hash code for a #agus_maps_flutterPlacePageIntMetadataEntry object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_place_page_int_metadata_entry_hash(agus_maps_flutterPlacePageIntMetadataEntry* object);

/**
 * agus_maps_flutterPlacePageStringMetadataEntry:
 *
 * String-keyed metadata entry.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterPlacePageStringMetadataEntry, agus_maps_flutter_place_page_string_metadata_entry, AGUS_MAPS_FLUTTER, PLACE_PAGE_STRING_METADATA_ENTRY, GObject)

/**
 * agus_maps_flutter_place_page_string_metadata_entry_new:
 * key: field in this object.
 * value: field in this object.
 *
 * Creates a new #PlacePageStringMetadataEntry object.
 *
 * Returns: a new #agus_maps_flutterPlacePageStringMetadataEntry
 */
agus_maps_flutterPlacePageStringMetadataEntry* agus_maps_flutter_place_page_string_metadata_entry_new(const gchar* key, const gchar* value);

/**
 * agus_maps_flutter_place_page_string_metadata_entry_get_key
 * @object: a #agus_maps_flutterPlacePageStringMetadataEntry.
 *
 * Gets the value of the key field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_string_metadata_entry_get_key(agus_maps_flutterPlacePageStringMetadataEntry* object);

/**
 * agus_maps_flutter_place_page_string_metadata_entry_get_value
 * @object: a #agus_maps_flutterPlacePageStringMetadataEntry.
 *
 * Gets the value of the value field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_string_metadata_entry_get_value(agus_maps_flutterPlacePageStringMetadataEntry* object);

/**
 * agus_maps_flutter_place_page_string_metadata_entry_equals:
 * @a: a #agus_maps_flutterPlacePageStringMetadataEntry.
 * @b: another #agus_maps_flutterPlacePageStringMetadataEntry.
 *
 * Checks if two #agus_maps_flutterPlacePageStringMetadataEntry objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_place_page_string_metadata_entry_equals(agus_maps_flutterPlacePageStringMetadataEntry* a, agus_maps_flutterPlacePageStringMetadataEntry* b);

/**
 * agus_maps_flutter_place_page_string_metadata_entry_hash:
 * @object: a #agus_maps_flutterPlacePageStringMetadataEntry.
 *
 * Calculates a hash code for a #agus_maps_flutterPlacePageStringMetadataEntry object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_place_page_string_metadata_entry_hash(agus_maps_flutterPlacePageStringMetadataEntry* object);

/**
 * agus_maps_flutterPlacePageData:
 *
 * Structured place page payload.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterPlacePageData, agus_maps_flutter_place_page_data, AGUS_MAPS_FLUTTER, PLACE_PAGE_DATA, GObject)

/**
 * agus_maps_flutter_place_page_data_new:
 * feature_id: field in this object.
 * object_type: field in this object.
 * opening_mode: field in this object.
 * title: field in this object.
 * secondary_title: field in this object.
 * subtitle: field in this object.
 * address: field in this object.
 * lat: field in this object.
 * lon: field in this object.
 * wiki_description_html: field in this object.
 * road_type: field in this object.
 * is_route_point: field in this object.
 * coordinates: field in this object.
 * raw_types: field in this object.
 * metadata: field in this object.
 * metadata_tags: field in this object.
 * bookmark_id: field in this object.
 * bookmark_category_id: field in this object.
 * track_id: field in this object.
 *
 * Creates a new #PlacePageData object.
 *
 * Returns: a new #agus_maps_flutterPlacePageData
 */
agus_maps_flutterPlacePageData* agus_maps_flutter_place_page_data_new(agus_maps_flutterPlacePageFeatureId* feature_id, int64_t object_type, int64_t opening_mode, const gchar* title, const gchar* secondary_title, const gchar* subtitle, const gchar* address, double lat, double lon, const gchar* wiki_description_html, int64_t road_type, gboolean is_route_point, agus_maps_flutterPlacePageCoordinates* coordinates, FlValue* raw_types, FlValue* metadata, FlValue* metadata_tags, int64_t* bookmark_id, int64_t* bookmark_category_id, int64_t* track_id);

/**
 * agus_maps_flutter_place_page_data_get_feature_id
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the featureId field of @object.
 *
 * Returns: the field value.
 */
agus_maps_flutterPlacePageFeatureId* agus_maps_flutter_place_page_data_get_feature_id(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_object_type
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the objectType field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_place_page_data_get_object_type(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_opening_mode
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the openingMode field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_place_page_data_get_opening_mode(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_title
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the title field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_data_get_title(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_secondary_title
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the secondaryTitle field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_data_get_secondary_title(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_subtitle
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the subtitle field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_data_get_subtitle(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_address
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the address field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_data_get_address(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_lat
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the lat field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_place_page_data_get_lat(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_lon
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the lon field of @object.
 *
 * Returns: the field value.
 */
double agus_maps_flutter_place_page_data_get_lon(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_wiki_description_html
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the wikiDescriptionHtml field of @object.
 *
 * Returns: the field value.
 */
const gchar* agus_maps_flutter_place_page_data_get_wiki_description_html(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_road_type
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the roadType field of @object.
 *
 * Returns: the field value.
 */
int64_t agus_maps_flutter_place_page_data_get_road_type(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_is_route_point
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the isRoutePoint field of @object.
 *
 * Returns: the field value.
 */
gboolean agus_maps_flutter_place_page_data_get_is_route_point(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_coordinates
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the coordinates field of @object.
 *
 * Returns: the field value.
 */
agus_maps_flutterPlacePageCoordinates* agus_maps_flutter_place_page_data_get_coordinates(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_raw_types
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the rawTypes field of @object.
 *
 * Returns: the field value.
 */
FlValue* agus_maps_flutter_place_page_data_get_raw_types(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_metadata
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the metadata field of @object.
 *
 * Returns: the field value.
 */
FlValue* agus_maps_flutter_place_page_data_get_metadata(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_metadata_tags
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the metadataTags field of @object.
 *
 * Returns: the field value.
 */
FlValue* agus_maps_flutter_place_page_data_get_metadata_tags(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_bookmark_id
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the bookmarkId field of @object.
 *
 * Returns: the field value.
 */
int64_t* agus_maps_flutter_place_page_data_get_bookmark_id(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_bookmark_category_id
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the bookmarkCategoryId field of @object.
 *
 * Returns: the field value.
 */
int64_t* agus_maps_flutter_place_page_data_get_bookmark_category_id(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_get_track_id
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Gets the value of the trackId field of @object.
 *
 * Returns: the field value.
 */
int64_t* agus_maps_flutter_place_page_data_get_track_id(agus_maps_flutterPlacePageData* object);

/**
 * agus_maps_flutter_place_page_data_equals:
 * @a: a #agus_maps_flutterPlacePageData.
 * @b: another #agus_maps_flutterPlacePageData.
 *
 * Checks if two #agus_maps_flutterPlacePageData objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean agus_maps_flutter_place_page_data_equals(agus_maps_flutterPlacePageData* a, agus_maps_flutterPlacePageData* b);

/**
 * agus_maps_flutter_place_page_data_hash:
 * @object: a #agus_maps_flutterPlacePageData.
 *
 * Calculates a hash code for a #agus_maps_flutterPlacePageData object.
 *
 * Returns: the hash code.
 */
guint agus_maps_flutter_place_page_data_hash(agus_maps_flutterPlacePageData* object);

G_DECLARE_FINAL_TYPE(agus_maps_flutterMessageCodec, agus_maps_flutter_message_codec, AGUS_MAPS_FLUTTER, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int agus_maps_flutter_render_state_type_id;
extern const int agus_maps_flutter_create_map_surface_request_type_id;
extern const int agus_maps_flutter_resize_map_surface_request_type_id;
extern const int agus_maps_flutter_map_pointer_update_request_type_id;
extern const int agus_maps_flutter_map_pointer_coordinate_type_id;
extern const int agus_maps_flutter_drape_interaction_line_style_type_id;
extern const int agus_maps_flutter_drape_interaction_geometry_request_type_id;
extern const int agus_maps_flutter_place_page_feature_id_type_id;
extern const int agus_maps_flutter_place_page_coordinates_type_id;
extern const int agus_maps_flutter_place_page_int_metadata_entry_type_id;
extern const int agus_maps_flutter_place_page_string_metadata_entry_type_id;
extern const int agus_maps_flutter_place_page_data_type_id;

G_DECLARE_FINAL_TYPE(agus_maps_flutterAgusMapsHostApi, agus_maps_flutter_agus_maps_host_api, AGUS_MAPS_FLUTTER, AGUS_MAPS_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(agus_maps_flutterAgusMapsHostApiResponseHandle, agus_maps_flutter_agus_maps_host_api_response_handle, AGUS_MAPS_FLUTTER, AGUS_MAPS_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * agus_maps_flutterAgusMapsHostApiVTable:
 *
 * Table of functions exposed by AgusMapsHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*extract_map)(const gchar* asset_path, agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*extract_data_files)(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_apk_path)(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*create_map_surface)(agus_maps_flutterCreateMapSurfaceRequest* request, agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*resize_map_surface)(agus_maps_flutterResizeMapSurfaceRequest* request, agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*destroy_map_surface)(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*update_map_pointer)(agus_maps_flutterMapPointerUpdateRequest* request, agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*update_drape_interaction_geometry)(agus_maps_flutterDrapeInteractionGeometryRequest* request, agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_current_place_page)(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
  void (*clear_place_page_selection)(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gpointer user_data);
} agus_maps_flutterAgusMapsHostApiVTable;

/**
 * agus_maps_flutter_agus_maps_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the AgusMapsHostApi API.
 */
void agus_maps_flutter_agus_maps_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const agus_maps_flutterAgusMapsHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * agus_maps_flutter_agus_maps_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the AgusMapsHostApi API.
 */
void agus_maps_flutter_agus_maps_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_extract_map:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.extractMap. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_extract_map(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_extract_map:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.extractMap. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_extract_map(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_extract_data_files:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.extractDataFiles. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_extract_data_files(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_extract_data_files:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.extractDataFiles. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_extract_data_files(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_get_apk_path:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.getApkPath. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_get_apk_path(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_get_apk_path:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.getApkPath. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_get_apk_path(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_create_map_surface:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.createMapSurface. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_create_map_surface(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, int64_t return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_create_map_surface:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.createMapSurface. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_create_map_surface(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_resize_map_surface:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.resizeMapSurface. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_resize_map_surface(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_resize_map_surface:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.resizeMapSurface. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_resize_map_surface(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_destroy_map_surface:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.destroyMapSurface. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_destroy_map_surface(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_destroy_map_surface:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.destroyMapSurface. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_destroy_map_surface(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_update_map_pointer:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.updateMapPointer. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_update_map_pointer(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, agus_maps_flutterMapPointerCoordinate* return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_update_map_pointer:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.updateMapPointer. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_update_map_pointer(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_update_drape_interaction_geometry:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.updateDrapeInteractionGeometry. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_update_drape_interaction_geometry(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_update_drape_interaction_geometry:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.updateDrapeInteractionGeometry. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_update_drape_interaction_geometry(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_get_current_place_page:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.getCurrentPlacePage. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_get_current_place_page(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, agus_maps_flutterPlacePageData* return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_get_current_place_page:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.getCurrentPlacePage. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_get_current_place_page(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_clear_place_page_selection:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AgusMapsHostApi.clearPlacePageSelection. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_clear_place_page_selection(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * agus_maps_flutter_agus_maps_host_api_respond_error_clear_place_page_selection:
 * @response_handle: a #agus_maps_flutterAgusMapsHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AgusMapsHostApi.clearPlacePageSelection. 
 */
void agus_maps_flutter_agus_maps_host_api_respond_error_clear_place_page_selection(agus_maps_flutterAgusMapsHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse, agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response, AGUS_MAPS_FLUTTER, AGUS_MAPS_FLUTTER_API_ON_MAP_READY_RESPONSE, GObject)

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_is_error:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse.
 *
 * Checks if a response to AgusMapsFlutterApi.onMapReady is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_is_error(agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_get_error_code:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_get_error_code(agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_get_error_message:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_get_error_message(agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_get_error_details:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* agus_maps_flutter_agus_maps_flutter_api_on_map_ready_response_get_error_details(agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse* response);

G_DECLARE_FINAL_TYPE(agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse, agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response, AGUS_MAPS_FLUTTER, AGUS_MAPS_FLUTTER_API_ON_RENDER_STATE_CHANGED_RESPONSE, GObject)

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_is_error:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse.
 *
 * Checks if a response to AgusMapsFlutterApi.onRenderStateChanged is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_is_error(agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_get_error_code:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_get_error_code(agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_get_error_message:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_get_error_message(agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_get_error_details:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_response_get_error_details(agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse* response);

G_DECLARE_FINAL_TYPE(agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse, agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response, AGUS_MAPS_FLUTTER, AGUS_MAPS_FLUTTER_API_ON_PLACE_PAGE_CHANGED_RESPONSE, GObject)

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_is_error:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse.
 *
 * Checks if a response to AgusMapsFlutterApi.onPlacePageChanged is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_is_error(agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_get_error_code:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_get_error_code(agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_get_error_message:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_get_error_message(agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse* response);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_get_error_details:
 * @response: a #agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_response_get_error_details(agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse* response);

/**
 * agus_maps_flutterAgusMapsFlutterApi:
 *
 * Flutter API implemented by Dart for low-frequency notifications.
 */

G_DECLARE_FINAL_TYPE(agus_maps_flutterAgusMapsFlutterApi, agus_maps_flutter_agus_maps_flutter_api, AGUS_MAPS_FLUTTER, AGUS_MAPS_FLUTTER_API, GObject)

/**
 * agus_maps_flutter_agus_maps_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the AgusMapsFlutterApi API.
 *
 * Returns: a new #agus_maps_flutterAgusMapsFlutterApi
 */
agus_maps_flutterAgusMapsFlutterApi* agus_maps_flutter_agus_maps_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_map_ready:
 * @api: a #agus_maps_flutterAgusMapsFlutterApi.
 * @surface_id: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void agus_maps_flutter_agus_maps_flutter_api_on_map_ready(agus_maps_flutterAgusMapsFlutterApi* api, int64_t surface_id, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_map_ready_finish:
 * @api: a #agus_maps_flutterAgusMapsFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a agus_maps_flutter_agus_maps_flutter_api_on_map_ready() call.
 *
 * Returns: a #agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse or %NULL on error.
 */
agus_maps_flutterAgusMapsFlutterApiOnMapReadyResponse* agus_maps_flutter_agus_maps_flutter_api_on_map_ready_finish(agus_maps_flutterAgusMapsFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed:
 * @api: a #agus_maps_flutterAgusMapsFlutterApi.
 * @state: parameter for this method.
 * @surface_id: (allow-none): parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed(agus_maps_flutterAgusMapsFlutterApi* api, agus_maps_flutterRenderState state, int64_t* surface_id, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_finish:
 * @api: a #agus_maps_flutterAgusMapsFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed() call.
 *
 * Returns: a #agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse or %NULL on error.
 */
agus_maps_flutterAgusMapsFlutterApiOnRenderStateChangedResponse* agus_maps_flutter_agus_maps_flutter_api_on_render_state_changed_finish(agus_maps_flutterAgusMapsFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed:
 * @api: a #agus_maps_flutterAgusMapsFlutterApi.
 * @place_page: (allow-none): parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed(agus_maps_flutterAgusMapsFlutterApi* api, agus_maps_flutterPlacePageData* place_page, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_finish:
 * @api: a #agus_maps_flutterAgusMapsFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed() call.
 *
 * Returns: a #agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse or %NULL on error.
 */
agus_maps_flutterAgusMapsFlutterApiOnPlacePageChangedResponse* agus_maps_flutter_agus_maps_flutter_api_on_place_page_changed_finish(agus_maps_flutterAgusMapsFlutterApi* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_AGUS_MAPS_API_G_H_
